import {test,expect,_electron as electron,type ElectronApplication,type Page} from '@playwright/test';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
const run=promisify(execFile);
const evidenceDir=resolve('test-results/echo');
async function native(action:string,folder:string,date='2026-10-05',files=['audio_01.wav','audio_02.wav'],newName='off_audio_01',outputPath=''){
  // PS receives a string-array through a literal script, avoiding shell interpolation of paths.
  const args=['-NoProfile','-ExecutionPolicy','Bypass','-File',resolve('tests/e2e/echo-explorer.ps1'),'-Action',action,'-Folder',folder,'-DateFolder',date,'-NewName',newName];
  if(files.length===1)args.push('-Files',files[0]!);if(outputPath)args.push('-OutputPath',outputPath);
  return run('powershell.exe',args,{windowsHide:true,timeout:20000});
}
async function launch(profile:string){const env:NodeJS.ProcessEnv={...process.env,AETHER_TEST_PROFILE:profile};delete env.ELECTRON_RUN_AS_NODE;return electron.launch({args:[resolve('.')],env:env as Record<string,string>});}
async function echoPage(app:ElectronApplication,entity:Page){await entity.evaluate(()=>window.aether.command('echo'));await expect.poll(()=>app.windows().some(p=>p.url().endsWith('#echo'))).toBe(true);const page=app.windows().find(p=>p.url().endsWith('#echo'))!;await page.getByRole('heading',{name:'Regarde comment je fais.'}).waitFor();return page;}
const snapshot=(p:Page)=>p.evaluate(()=>window.aether.getEcho());
async function choose(page:Page,folder:string){
  const clicked=page.getByRole('button',{name:'Choisir le dossier de test'}).click();
  await page.waitForTimeout(500);await native('picker',folder);await clicked;
  await expect(page.getByTestId('echo-folder')).toHaveText(folder,{timeout:5000});
}
async function begin(page:Page,folder:string){if(!(await snapshot(page)).enabled)await page.getByRole('button',{name:'Préparer une session ECHO'}).click();await choose(page,folder);await page.getByRole('checkbox',{name:/J’autorise/}).check();await page.getByRole('button',{name:'Démarrer l’observation'}).click();await expect.poll(async()=>(await snapshot(page)).state).toBe('observing');await native('open',folder);await expect.poll(async()=>(await snapshot(page)).context?.allowed,{timeout:15000}).toBe(true);}
async function stop(page:Page){await page.getByRole('button',{name:'Arrêter et comprendre'}).click();await expect.poll(async()=>(await snapshot(page)).state,{timeout:125000}).toBe('ready');return snapshot(page);}

test('ECHO A-I: explicit consent, actual native Explorer events, real local MIND, habits, repeat, correction, deletion, OFF and exclusion',async()=>{
  test.skip(process.platform!=='win32');test.setTimeout(240000);
  await mkdir(evidenceDir,{recursive:true});const profile=await mkdtemp(join(tmpdir(),'aether-j5-profile-')),folder=await mkdtemp(join(evidenceDir,'files-'));let app:ElectronApplication|undefined;
  const proofs:Record<string,unknown>={startedAt:new Date().toISOString(),observationSource:'Actual fs.watch + metadata diff + actual Win32/Shell foreground context',nativeActions:'Explorer F2, Ctrl+Shift+N, Ctrl+X/Ctrl+V',folderPicker:'Actual native directory picker',model:'Ollama qwen3.5:9b, no provider mock',profile};
  try{
    await writeFile(join(profile,'ai-settings.json'),JSON.stringify({schemaVersion:1,provider:'ollama',model:'qwen3.5:9b',ollamaUrl:'http://127.0.0.1:11434',cloudConsent:false}));await writeFile(join(profile,'router-settings.json'),JSON.stringify({schemaVersion:1,profiles:{DEEP:{provider:'ollama',model:'qwen3.5:9b'},VISION:null}}));
    await Promise.all(['audio_01.wav','audio_02.wav'].map(name=>writeFile(join(folder,name),'J5 controlled test file; contents never read by ECHO')));
    app=await launch(profile);
    // Fixture changes only the picker's initial directory, never its result or authorization.
    await app.evaluate(({dialog},root)=>{const original=dialog.showOpenDialog.bind(dialog);dialog.showOpenDialog=((owner:Electron.BrowserWindow,options:Electron.OpenDialogOptions)=>original(owner,{...options,defaultPath:options.title?.includes('exclure')?root+'\\private':root})) as typeof dialog.showOpenDialog;},folder);
    const entity=await app.firstWindow();await entity.getByRole('button',{name:'ENTITY — cliquer ou déplacer'}).waitFor();const panel=await echoPage(app,entity);
    expect((await snapshot(panel)).state).toBe('off');expect((await snapshot(panel)).sessions).toHaveLength(0);
    const rejected=await entity.evaluate(()=>window.aether.startEcho({token:'fake',consent:true})).catch(e=>String(e));expect(String(rejected)).toMatch(/panneau|ECHO/);
    await panel.getByRole('button',{name:'Préparer une session ECHO'}).click();await choose(panel,folder);expect((await snapshot(panel)).sessions).toHaveLength(0);await expect(panel.getByRole('button',{name:'Démarrer l’observation'})).toBeDisabled();await panel.screenshot({path:join(evidenceDir,'A-consent.png'),fullPage:true});
    
    await panel.getByRole('checkbox',{name:/J’autorise/}).check();await panel.getByRole('button',{name:'Démarrer l’observation'}).click();await native('open',folder);await expect.poll(async()=>(await snapshot(panel)).context?.allowed,{timeout:15000}).toBe(true);proofs.A={result:'PASS',explicitConsent:true,noSessionBeforeValidation:true,foreignWindowRejected:String(rejected)};
    await expect.poll(async()=>(await entity.evaluate(()=>window.aether.getSnapshot())).echoActive).toBe(true);await entity.screenshot({path:join(evidenceDir,'B-entity-active.png'),omitBackground:true});
    proofs.nativeFirst=await native('procedure',folder);const live=await snapshot(panel);proofs.observationDiagnostic=live;expect(live.sessions[0]!.events.some(e=>e.kind==='renamed')).toBe(true);expect(live.sessions[0]!.events.some(e=>e.kind==='moved')).toBe(true);expect(live.sessions[0]!.events.some(e=>e.kind==='created'&&e.nodeKind==='directory')).toBe(true);
    await native('capture',join(folder,'2026-10-05'),'2026-10-05',[], '',join(evidenceDir,'B-explorer.png'));proofs.B={result:'PASS',events:live.sessions[0]!.events};
    const first=await stop(panel),session=first.sessions[0]!,hyp=session.hypotheses[0]!;expect(hyp).toBeTruthy();expect(hyp.model).toBe('qwen3.5:9b');expect(hyp.route).toEqual({requested:'DEEP',selected:'DEEP',provider:'ollama',model:'qwen3.5:9b',fallback:false});expect(hyp.interpretation.description).toMatch(/date|dossier/i);expect(hyp.interpretation.description).toMatch(/nom|class|organis|structur/i);expect(hyp.interpretation.evidenceIds.every(id=>session.events.some(e=>e.id===id))).toBe(true);expect(await panel.evaluate(()=>window.aether.listMemories())).toHaveLength(0);proofs.C={result:'PASS',session};await panel.screenshot({path:join(evidenceDir,'C-hypothesis.png'),fullPage:true});
    await panel.getByRole('button',{name:'Oui, retenir cette habitude'}).click();const confirmed=(await snapshot(panel)).habits[0]!;expect(confirmed.state).toBe('confirmed');expect((await panel.evaluate(()=>window.aether.listMemories()))[0]!.kind).toBe('habit');
    await entity.evaluate(()=>window.aether.command('portal'));await expect.poll(()=>app!.windows().some(p=>p.url().endsWith('#space'))).toBe(true);const space=app.windows().find(p=>p.url().endsWith('#space'))!;await space.locator('.portal-shell[data-portal-phase="open"]').waitFor();await space.getByRole('button',{name:'ECHO',exact:true}).click();await expect(space.getByRole('heading',{name:'Habitudes confirmées'})).toBeVisible();expect((await space.evaluate(()=>window.aether.getSpace())).data.echo!.habits[0]!.id).toBe(confirmed.id);await space.screenshot({path:join(evidenceDir,'D-space.png')});await expect(space.locator('svg[aria-label="Habitudes ECHO reliées à MEMORY"]')).toBeVisible();const closing=space.waitForEvent('close');await space.getByRole('button',{name:/Revenir au bureau/}).click();await closing;proofs.D={result:'PASS',habit:confirmed,memory:await panel.evaluate(()=>window.aether.listMemories())};
    await native('close',join(folder,'2026-10-05'));await Promise.all(['audio_01.wav','audio_02.wav'].map(name=>writeFile(join(folder,name),'Second controlled occurrence')));await begin(panel,folder);proofs.nativeSecond=await native('procedure',folder,'2026-10-08');const second=await stop(panel);expect(second.habits).toHaveLength(1);expect(second.habits[0]!.id).toBe(confirmed.id);expect(second.habits[0]!.occurrences).toBe(2);const secondSession=second.sessions.find(s=>s.id!==session.id)!,secondHyp=secondSession.hypotheses[0]!;expect(secondHyp.habitId).toBe(confirmed.id);expect(second.habits[0]!.variations.some(v=>v.description.includes('2026-10-08')&&v.comparedSessionId===session.id&&v.evidenceIds.every(id=>secondSession.events.some(e=>e.id===id)))).toBe(true);proofs.E={result:'PASS',habit:second.habits[0],session:secondSession};
    const correction='Je prépare des lots WAV datés pour un export client. Ce classement temporaire ne décrit pas ma bibliothèque audio personnelle.';await panel.getByRole('button',{name:'Corriger l’interprétation'}).click();await panel.getByRole('textbox',{name:'Votre méthode réelle'}).fill(correction);await panel.getByRole('button',{name:'Valider ma correction et retenir'}).click();const corrected=await snapshot(panel);expect(corrected.habits[0]!.description).toBe(correction);expect(corrected.sessions.find(s=>s.id===secondSession.id)!.hypotheses[0]!.invalidated).toBe(true);proofs.F={result:'PASS',misunderstanding:'The model describes date-based audio filing without the known client-export purpose. The user corrects this incomplete interpretation.',before:secondHyp,after:corrected.sessions.find(s=>s.id===secondSession.id),habit:corrected.habits[0]};await panel.screenshot({path:join(evidenceDir,'F-correction.png'),fullPage:true});
    await panel.getByRole('button',{name:'Supprimer cette session',exact:true}).click();await panel.getByRole('button',{name:'Confirmer la suppression de session'}).click();const deleted=await snapshot(panel);expect(deleted.sessions.some(s=>s.id===secondSession.id)).toBe(false);expect(deleted.habits[0]!.occurrences).toBe(1);expect(deleted.habits[0]!.description).toBe(confirmed.description);proofs.G={result:'PASS',deletedSessionId:secondSession.id,remaining:deleted};
    await panel.getByRole('button',{name:'Désactiver complètement ECHO'}).click();const off=await snapshot(panel);await native('close',join(folder,'2026-10-08'));await native('open',folder);await writeFile(join(folder,'off.wav'),'OFF controlled file');await native('rename',folder,'', ['off.wav'],'off-renamed');await panel.waitForTimeout(500);const afterOff=await snapshot(panel);expect(afterOff.sessions).toEqual(off.sessions);expect(afterOff.state).toBe('off');proofs.H={result:'PASS',before:off,after:afterOff};
    const privateFolder=join(folder,'private');await mkdir(privateFolder);await writeFile(join(privateFolder,'private.wav'),'Excluded data');await panel.locator('.echo-exclusions summary').click();const chooseExcluded=panel.getByRole('button',{name:'Exclure un dossier'}).click();await panel.waitForTimeout(500);await native('picker',privateFolder);await chooseExcluded;await expect.poll(async()=>(await snapshot(panel)).exclusions.folders).toContain(privateFolder);await begin(panel,folder);await native('open',privateFolder);await native('rename',privateFolder,'',['private.wav'],'private-renamed');await panel.waitForTimeout(500);const excluded=await snapshot(panel);const exclusionSession=excluded.sessions.find(s=>s.id===excluded.activeSessionId)!;expect(exclusionSession.events).toHaveLength(0);await panel.getByRole('button',{name:'Arrêter et comprendre'}).click();await expect.poll(async()=>(await snapshot(panel)).state).toBe('ready');proofs.I={result:'PASS',excludedFolder:privateFolder,events:exclusionSession.events,confirmedMemory:await panel.evaluate(()=>window.aether.listMemories())};
    const beforeRestart=await snapshot(panel);await app.close();app=await launch(profile);const restarted=await app.firstWindow();await restarted.getByRole('button',{name:'ENTITY — cliquer ou déplacer'}).waitFor();const actual=await restarted.evaluate(()=>window.aether.getEcho());expect(actual.state).toBe('off');expect(actual.enabled).toBe(false);expect(actual.habits[0]!.id).toBe(confirmed.id);expect(actual.sessions.length).toBe(beforeRestart.sessions.length);proofs.restart={result:'PASS',snapshot:actual};
    proofs.finishedAt=new Date().toISOString();proofs.result='PASS';await writeFile(join(evidenceDir,'preuve-reelle.json'),JSON.stringify(proofs,null,2));
  }finally{
    if(app)await app.close();await writeFile(join(evidenceDir,'preuve-en-cours.json'),JSON.stringify(proofs,null,2));
    for(const path of [folder,join(folder,'2026-10-05'),join(folder,'2026-10-08'),join(folder,'private')])await native('close',path).catch(()=>{});
    await rm(profile,{recursive:true,force:true});await rm(folder,{recursive:true,force:true});
  }
});
