import {test,expect,_electron as electron,type ElectronApplication,type Page} from '@playwright/test';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {importJ3Receipt} from './space-fixture';
const run=promisify(execFile);
async function input(action:string,x=0,y=0,shortcut='Control+Alt+A'){await run('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',resolve('tests/e2e/win32-input.ps1'),'-Action',action,'-X',String(x),'-Y',String(y),'-Shortcut',shortcut],{windowsHide:true});}
async function launch(profile:string){const env:Record<string,string>={};for(const [key,value] of Object.entries(process.env))if(typeof value==='string')env[key]=value;env.AETHER_TEST_PROFILE=profile;delete env.ELECTRON_RUN_AS_NODE;delete env.OPENAI_API_KEY;const app=await electron.launch({args:[resolve('.')],env});const entity=await app.firstWindow();await expect(entity.locator('.entity-stage')).toBeVisible();return {app,entity};}
async function open(app:ElectronApplication,entity:Page,name:'settings'|'memory'|'curiosity'|'space'){
  const command=name==='space'?'portal' as const:name;expect((await entity.evaluate(command=>window.aether.command(command),command)).ok).toBe(true);
  await expect.poll(()=>app.windows().some(page=>page.url().endsWith(`#${name}`))).toBe(true);
  const page=app.windows().find(page=>page.url().endsWith(`#${name}`))!;await page.waitForLoadState('domcontentloaded');return page;
}
const desktopBounds=(app:ElectronApplication)=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.getTitle()==='AETHER · ENTITY')!.getBounds());

test('J4 A–G: native portal, real J3 constellation and new local exploration, memory edits and restart',async()=>{
  test.setTimeout(360000);const profile=await mkdtemp(join(tmpdir(),'aether-j4-real-')),source=importJ3Receipt(profile);
  let app:ElectronApplication|undefined;const proof:Record<string,unknown>={startedAt:new Date().toISOString(),mock:false,source:'docs/recette-j4/source-j3.json',profile:'isolated temporary profile; no import into personal profile'};
  try{
    let launched=await launch(profile);app=launched.app;let entity=launched.entity;
    const settings=await open(app,entity,'settings');await settings.getByLabel('Fournisseur',{exact:true}).selectOption('ollama');await settings.getByLabel('Modèle',{exact:true}).fill('qwen3.5:9b');await settings.getByRole('button',{name:'Enregistrer l’IA',exact:true}).click();
    await expect(settings.getByRole('status').filter({hasText:'Configuration IA enregistrée.'})).toBeVisible();
    await settings.getByLabel('Fournisseur DEEP',{exact:true}).selectOption('ollama');await settings.getByLabel('Modèle DEEP',{exact:true}).fill('qwen3.5:9b');await settings.getByRole('button',{name:'Enregistrer les profils',exact:true}).click();await expect(settings.locator('.router-settings')).toContainText('Profils enregistrés.');
    expect((await entity.evaluate(()=>window.aether.savePortalSettings({shortcut:'Control+Alt+F9'}))).ok).toBe(false);
    expect(await app.evaluate(({globalShortcut})=>globalShortcut.register('Control+Alt+F12',()=>{}))).toBe(true);
    expect((await settings.evaluate(()=>window.aether.savePortalSettings({shortcut:'Control+Alt+F12'}))).ok).toBe(false);
    expect((await settings.evaluate(()=>window.aether.getPortalSettings())).shortcut).toBe('Control+Alt+A');
    await app.evaluate(({globalShortcut})=>globalShortcut.unregister('Control+Alt+F12'));
    await settings.getByLabel('Raccourci du portail',{exact:true}).focus();await settings.keyboard.press('Control+Alt+F9');await settings.getByRole('button',{name:'Enregistrer le portail',exact:true}).click();await expect(settings.locator('.portal-settings')).toContainText('Raccourci PORTAL enregistré.');
    const memories=await open(app,entity,'memory');await memories.getByRole('button',{name:'Ajouter',exact:true}).click();await memories.getByLabel('Contenu',{exact:true}).fill('Recette J4 : la constellation représente les objets persistants.');await memories.getByRole('button',{name:'Enregistrer le souvenir',exact:true}).click();
    const originalMemory=(await memories.evaluate(()=>window.aether.listMemories('')))[0]!;
    const journal=await open(app,entity,'curiosity');await journal.getByRole('checkbox',{name:'Exploration autonome',exact:true}).check();
    await expect.poll(async()=>{const snapshot=await journal.evaluate(()=>window.aether.getCuriosity());return snapshot.sessionAttempts===1&&snapshot.state!=='exploring';},{timeout:140000,intervals:[250,500,1000]}).toBe(true);
    const explored=await journal.evaluate(()=>window.aether.getCuriosity()),attempt=explored.explorations.find(item=>!source.explorations.some(old=>old.id===item.id))!;
    expect(attempt.status,JSON.stringify(attempt)).toBe('succeeded');expect(attempt.route).toEqual({requested:'DEEP',selected:'DEEP',provider:'ollama',model:'qwen3.5:9b',fallback:false});await journal.getByRole('checkbox',{name:'Exploration autonome',exact:true}).uncheck();proof.F_explorationBeforePortal=attempt;
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(window=>window.getTitle()!=='AETHER · ENTITY').forEach(window=>window.close()));
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.getTitle()==='AETHER · ENTITY')!.moveTop());
    await entity.evaluate(()=>{const probe=window as unknown as {portalEvents:unknown[]};probe.portalEvents=[];window.aether.onPortal(snapshot=>probe.portalEvents.push({...snapshot,receivedAt:Date.now()}));});
    const origin=await desktopBounds(app),physical=await app.evaluate(({screen},point)=>screen.dipToScreenPoint(point),{x:origin.x+80,y:origin.y+80});await input('move',physical.x,physical.y);await input('doubleclick');
    await expect.poll(()=>app!.windows().some(page=>page.url().endsWith('#space'))).toBe(true);let space=app.windows().find(page=>page.url().endsWith('#space'))!;
    await space.waitForLoadState('domcontentloaded');const transition=await space.evaluate(()=>({portal:document.querySelector('.portal-shell')?.getAttribute('data-portal-phase'),animation:document.querySelector('.space-universe')?getComputedStyle(document.querySelector('.space-universe')!).animationName:null}));proof.A_visualTransition=transition;if(transition.portal==='opening')await space.screenshot({path:'docs/recette-j4/A-portal.png'});
    await expect(space.locator('.portal-shell')).toHaveAttribute('data-portal-phase','open');expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.getTitle()==='AETHER · ENTITY')!.isVisible())).toBe(false);
    const real=await space.evaluate(()=>window.aether.getSpace());expect(real.data.memories).toEqual(await space.evaluate(()=>window.aether.listMemories('')));expect(real.data.curiosity?.interests).toEqual((await entity.evaluate(()=>window.aether.getCuriosity())).interests);
    expect(await space.evaluate(()=>({require:typeof (window as unknown as {require:unknown}).require,process:typeof (window as unknown as {process:unknown}).process}))).toEqual({require:'undefined',process:'undefined'});
    expect((await entity.evaluate(()=>window.aether.saveSpace({camera:{x:0,y:0,zoom:1},labels:true,depth:true,selection:null}))).ok).toBe(false);
    expect((await space.evaluate(()=>window.aether.saveSpace({camera:{x:0,y:0,zoom:Infinity},labels:true,depth:true,selection:null}))).ok).toBe(false);
    await space.screenshot({path:'docs/recette-j4/A-space.png'});proof.A_entry={method:'native Windows double-click',origin,portal:real.portal,permissions:real.data.presence.permissions};proof.C_data={memory:originalMemory,interests:real.data.curiosity?.interests};
    await space.mouse.move(100,300);await space.mouse.down();await space.mouse.move(150,345);await space.mouse.up();await expect.poll(async()=>JSON.parse(await readFile(join(profile,'space-state.json'),'utf8')).camera.x).toBe(50);await space.mouse.wheel(0,-80);await expect.poll(async()=>Number(await space.locator('.space-stage').getAttribute('data-zoom'))).toBeGreaterThan(.86);proof.navigation={pan:{x:50,y:45},wheelZoom:true,keyboard:true};
    const causal=source.interests.find(item=>item.title==='Causalité structurelle')!;await space.locator(`[data-interest-id="${causal.id}"]`).click();
    const inspector=space.locator('.space-inspector');await expect(inspector.getByRole('heading',{name:'Causalité structurelle',exact:true})).toBeVisible();
    expect(await inspector.getByRole('region',{name:'Historique de l’intérêt'}).locator('article').count()).toBe(explored.history.filter(item=>item.interestId===causal.id).length);
    const questions=explored.items.filter(item=>item.interestId===causal.id&&item.kind==='question');for(const question of questions)await expect(inspector.getByRole('region',{name:'Questions de l’intérêt'})).toContainText(question.content);
    await space.screenshot({path:'docs/recette-j4/D-interest.png'});proof.D_interest={id:causal.id,questions:questions.map(item=>item.id),history:explored.history.filter(item=>item.interestId===causal.id)};
    const edge=source.connections[0]!;await space.getByRole('button',{name:'Fermer les détails',exact:true}).click();await space.locator(`[data-connection-id="${edge.id}"]`).focus();await space.keyboard.press('Enter');await expect(inspector).toContainText(edge.description);await expect(inspector).toContainText('Acoustique des résonateurs');await space.screenshot({path:'docs/recette-j4/E-connection.png'});proof.E_connection=edge;
    await space.getByRole('button',{name:'Fermer les détails',exact:true}).click();await space.getByRole('navigation',{name:'Zones de SPACE'}).getByRole('button',{name:/ACTIVITY/}).click();await expect(space.locator(`[data-activity-id="exploration:${attempt.id}"]`)).toContainText(attempt.reason);await space.screenshot({path:'docs/recette-j4/F-activity.png'});
    await space.getByRole('button',{name:'Fermer les détails',exact:true}).click();await space.getByRole('navigation',{name:'Zones de SPACE'}).getByRole('button',{name:'MEMORY',exact:true}).click();const embedded=space.locator('.memory-embedded');await expect(embedded).toContainText(originalMemory.content);await embedded.getByRole('button',{name:'Corriger',exact:true}).click();await embedded.getByLabel('Contenu',{exact:true}).fill('Recette J4 : souvenir corrigé depuis SPACE.');await embedded.getByRole('button',{name:'Enregistrer le souvenir',exact:true}).click();await expect(embedded).toContainText('Recette J4 : souvenir corrigé depuis SPACE.');
    await embedded.getByRole('button',{name:'Supprimer',exact:true}).click();await embedded.getByRole('button',{name:'Confirmer la suppression',exact:true}).click();await expect.poll(async()=>(await space.evaluate(()=>window.aether.getSpace())).data.memories.length).toBe(0);proof.C_memoryMutation={id:originalMemory.id,corrected:true,deleted:true};
    await space.getByRole('button',{name:'Fermer les détails',exact:true}).click();await space.getByRole('button',{name:'Zoomer',exact:true}).click();await space.locator('.space-stage').focus();await space.keyboard.press('ArrowLeft');await space.keyboard.press('ArrowUp');await space.getByText('Affichage',{exact:true}).click();await space.getByLabel('Profondeur légère').uncheck();
    await space.locator(`[data-interest-id="${causal.id}"]`).click();await expect.poll(async()=>JSON.parse(await readFile(join(profile,'space-state.json'),'utf8')).selection?.id).toBe(causal.id);
    const saved=JSON.parse(await readFile(join(profile,'space-state.json'),'utf8'));expect(saved.camera.zoom).toBeGreaterThan(.86);expect(saved.depth).toBe(false);
    await space.keyboard.press('Escape');await expect.poll(()=>app!.windows().some(page=>page.url().endsWith('#space'))).toBe(false);expect(await desktopBounds(app)).toMatchObject({x:origin.x,y:origin.y});proof.B_exit={method:'Escape',returnedBounds:await desktopBounds(app),spaceWindowDestroyed:true};
    await input('shortcut',0,0,'Control+Alt+F9');await expect.poll(()=>app!.windows().some(page=>page.url().endsWith('#space'))).toBe(true);space=app.windows().find(page=>page.url().endsWith('#space'))!;await expect(space.locator('.portal-shell')).toHaveAttribute('data-portal-phase','open');await input('shortcut',0,0,'Control+Alt+F9');await expect.poll(()=>app!.windows().some(page=>page.url().endsWith('#space'))).toBe(false);
    proof.A_B_transitionEvents=await entity.evaluate(()=>(window as unknown as {portalEvents:unknown[]}).portalEvents);
    await app.close();app=undefined;launched=await launch(profile);app=launched.app;entity=launched.entity;space=await open(app,entity,'space');await expect(space.locator('.portal-shell')).toHaveAttribute('data-portal-phase','open');await expect(space.locator('.space-inspector')).toContainText('Causalité structurelle');const restored=await space.evaluate(()=>window.aether.getSpace());expect(restored.preferences.camera).toEqual(saved.camera);expect(restored.preferences.depth).toBe(false);expect(restored.preferences.selection).toEqual(saved.selection);expect(restored.since).not.toBeNull();expect(restored.data.curiosity?.items).toEqual(explored.items);expect(restored.data.curiosity?.connections).toEqual(explored.connections);expect(restored.data.curiosity?.settings.enabled).toBe(false);await space.screenshot({path:'docs/recette-j4/G-restart.png'});proof.G_restart={preferences:restored.preferences,since:restored.since,interests:restored.data.curiosity?.interests.length,explorations:restored.data.curiosity?.explorations.length};
    await space.getByRole('button',{name:/Revenir au bureau/}).click();await expect.poll(()=>app!.windows().some(page=>page.url().endsWith('#space'))).toBe(false);
    const reducedSettings=await open(app,entity,'settings');const prefs=(await entity.evaluate(()=>window.aether.getSnapshot())).preferences;expect((await reducedSettings.evaluate(recall=>window.aether.saveSettings({recallShortcut:recall,reducedMotion:true}),prefs.recallShortcut)).ok).toBe(true);space=await open(app,entity,'space');await expect(space.locator('.portal-shell')).toHaveClass(/reduce-motion/);await expect(space.locator('.portal-shell')).toHaveAttribute('data-portal-phase','open');expect((await space.evaluate(()=>window.aether.getPortal())).durationMs).toBe(90);await space.keyboard.press('Escape');await expect.poll(()=>app!.windows().some(page=>page.url().endsWith('#space'))).toBe(false);
    const rapid=await entity.evaluate(()=>Promise.all([window.aether.command('portal'),window.aether.command('recall'),window.aether.command('portal')]));expect(rapid.every(result=>result.ok)).toBe(true);await expect.poll(()=>app!.windows().filter(page=>page.url().endsWith('#space')).length).toBe(1);space=app.windows().find(page=>page.url().endsWith('#space'))!;await expect(space.locator('.portal-shell')).toHaveAttribute('data-portal-phase','open');await space.keyboard.press('Escape');await expect.poll(()=>app!.windows().some(page=>page.url().endsWith('#space'))).toBe(false);proof.rapidReentry=true;
    proof.result='PASS';proof.completedAt=new Date().toISOString();await writeFile('docs/recette-j4/preuve-reelle.json',JSON.stringify(proof,null,2));
  }finally{await app?.close();await rm(profile,{recursive:true,force:true});}
});
