import { useEffect,useState } from 'react';
import type { CuriosityObjectKind,CuriositySettings,InterestWrite,OperationResult } from '@aether/shared';
import { isBlocked } from '@aether/curiosity/policy';
import { useCuriosity } from './useCuriosity';

const ORIGIN={autonomous:'Réflexion autonome',conversation:'Conversation utilisateur',memory:'Souvenir local',mind:'Suggestion de MIND',interest:'Intérêt déjà exploré',connection:'Connexion entre intérêts',exploration:'Exploration précédente',user:'Piste proposée par l’utilisateur'};
const STATUS={active:'Actif',dormant:'Dormant',abandoned:'Abandonné'};
type Tab='interests'|'questions'|'discoveries'|'connections'|'explorations';
export function Curiosity() {
  const {snapshot,error:loadError}=useCuriosity();
  const [tab,setTab]=useState<Tab>('interests'),[draft,setDraft]=useState<InterestWrite|null>(null),[budget,setBudget]=useState<CuriositySettings|null>(null);
  const [error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[deletion,setDeletion]=useState<string|null>(null),[domain,setDomain]=useState('');
  useEffect(()=>{if(snapshot)setBudget({...snapshot.settings});},[snapshot?.settings.maxExplorations,snapshot?.settings.maxDurationSeconds,snapshot?.settings.minIntervalSeconds]);
  async function act(action:()=>Promise<OperationResult>,message?:string) {setError(null);try{const result=await action();if(!result.ok)setError(result.error);else if(message)setNotice(message);}catch(reason){setError(String(reason));}}
  function remove(kind:CuriosityObjectKind,id:string) {return deletion===id?<><span>Supprimer et retirer les éléments liés ?</span><button className="danger-button" onClick={()=>{void act(()=>window.aether.removeCuriosity(kind,id),'Objet supprimé et contexte réinitialisé.');setDeletion(null);}}>Confirmer la suppression</button><button className="text-button" onClick={()=>setDeletion(null)}>Annuler</button></>:<button className="text-button" onClick={()=>setDeletion(id)}>Supprimer</button>;}
  if(!snapshot)return <main className="curiosity-page"><p role="alert">{loadError??'Chargement du journal…'}</p></main>;
  const title=(id:string)=>snapshot.interests.find(item=>item.id===id)?.title ?? 'Piste retirée';
  return <main className="curiosity-page" data-curiosity-state={snapshot.state}>
    <header className="brand"><span className="brand-mark">◌</span><span>AETHER</span><span className="version">FIRST LIFE · 03</span></header>
    <section className="curiosity-intro"><p className="eyebrow">CURIOSITY</p><h1>Mon histoire intellectuelle</h1><p className="subtle">Des pistes que je poursuis, des questions qui évoluent, des relations que je propose. Une réflexion locale ; aucune recherche Web ni expérience exécutée.</p></section>
    <section className="curiosity-controls" aria-label="Autonomie et budget"><div className="autonomy-row"><label><input type="checkbox" aria-label="Exploration autonome" checked={snapshot.settings.enabled} onChange={event=>{void act(()=>window.aether.saveCuriositySettings({...snapshot.settings,enabled:event.target.checked}),event.target.checked?'Autonomie locale activée.':'Autonomie arrêtée.');}} /><strong>Exploration autonome</strong></label><span className="curiosity-state">{snapshot.state==='exploring'?'Réflexion locale en cours':snapshot.state==='disabled'?'Désactivée':snapshot.state==='budget-exhausted'?'Budget épuisé':snapshot.state==='error'?'Exploration interrompue':'En attente de la prochaine piste'}</span></div>
      <p className="helper">En l’activant, vous autorisez ENTITY à réfléchir avec un modèle local à partir de son journal, du dernier échange et de souvenirs locaux pertinents. Aucun accès externe. Désactiver annule immédiatement l’appel en cours.</p>
      {budget && <form onSubmit={event=>{event.preventDefault();void act(()=>window.aether.saveCuriositySettings({...budget,enabled:snapshot.settings.enabled}),'Budget enregistré.');}}><div className="budget-fields">{([{key:'maxExplorations',label:'Explorations par session',max:50},{key:'maxDurationSeconds',label:'Temps de calcul par session (secondes)',max:3600},{key:'minIntervalSeconds',label:'Intervalle minimal (secondes)',max:86400}] as const).map(field=><label key={field.key} htmlFor={`curiosity-${field.key}`}>{field.label}<input id={`curiosity-${field.key}`} type="number" min={1} max={field.max} step={1} value={budget[field.key]} onChange={event=>setBudget({...budget,[field.key]:Number(event.target.value)})} /></label>)}</div><div className="curiosity-control-actions"><button className="secondary" type="submit">Enregistrer le budget</button><span>{snapshot.sessionAttempts} / {snapshot.settings.maxExplorations} essais · {Math.ceil(snapshot.sessionDurationMs/1000)} s de calcul</span></div></form>}
      <div className="curiosity-control-actions"><button disabled={!snapshot.settings.enabled||snapshot.state==='exploring'||snapshot.state==='budget-exhausted'} onClick={()=>{void act(()=>window.aether.curiosityControl('explore'));}}>Explorer maintenant</button><button className="text-button" disabled={snapshot.state!=='exploring'} onClick={()=>{void act(()=>window.aether.curiosityControl('cancel'),'Exploration annulée.');}}>Annuler la réflexion</button>{snapshot.unreadCount>0 && <button className="text-button" onClick={()=>{void act(()=>window.aether.markCuriosityRead());}}>Marquer les découvertes comme lues ({snapshot.unreadCount})</button>}</div>
      {snapshot.nextAt && <p className="helper">Prochaine possibilité : {new Date(snapshot.nextAt).toLocaleTimeString('fr-FR')}. Le dialogue humain garde la priorité.</p>}
    </section>
    {(error||loadError||snapshot.error) && <p role="alert" className="dialogue-error">{error||loadError||snapshot.error}</p>}{notice && <p role="status" className="saved-message">{notice}</p>}
    <nav className="curiosity-tabs" aria-label="Journal de curiosité">{([{key:'interests',label:'Ce qui m’intéresse'},{key:'questions',label:'Ce que j’essaie de comprendre'},{key:'discoveries',label:'Ce que j’ai découvert'},{key:'connections',label:'Connexions'},{key:'explorations',label:'Explorations'}] as const).map(item=><button key={item.key} aria-pressed={tab===item.key} onClick={()=>{setTab(item.key);setDeletion(null);}}>{item.label}</button>)}</nav>
    {tab==='interests' && <section className="curiosity-interests"><div className="journal-heading"><h2>Mes centres d’intérêt</h2><button className="secondary" onClick={()=>setDraft({title:'',description:'',level:0.5,status:'active'})}>Proposer une piste</button></div>
      {draft && <form className="interest-editor" onSubmit={event=>{event.preventDefault();void act(async()=>{const result=await window.aether.writeInterest(draft);if(result.ok)setDraft(null);return result;},'Piste enregistrée.');}}><label htmlFor="interest-title">Titre de la piste</label><input id="interest-title" required maxLength={160} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} /><label htmlFor="interest-description">Description de la piste</label><textarea id="interest-description" required maxLength={1200} rows={2} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})} /><div className="interest-edit-options"><label htmlFor="interest-level">Priorité cognitive (0 à 1)<input id="interest-level" type="number" min={0} max={1} step={0.05} value={draft.level} onChange={event=>setDraft({...draft,level:Number(event.target.value)})} /></label><label htmlFor="interest-status">Statut de la piste<select id="interest-status" value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value as InterestWrite['status']})}><option value="active">Actif / réactiver</option><option value="dormant">Dormant</option><option value="abandoned">Abandonné</option></select></label></div><div className="journal-actions"><button type="submit">Enregistrer la piste</button><button className="text-button" type="button" onClick={()=>setDraft(null)}>Annuler</button></div></form>}
      {!snapshot.interests.length && <p className="journal-empty">Aucune piste pré-écrite. Une première exploration autorisée peut faire naître un intérêt.</p>}
      {snapshot.interests.map(item=><article className="journal-card interest-card" data-interest-id={item.id} key={item.id}><div className="journal-meta"><span>{STATUS[item.status]}{isBlocked(`${item.title} ${item.description}`,snapshot.blockedDomains)?' · domaine exclu':''}</span><span>Priorité {Math.round(item.level*100)} %</span></div><h3>{item.title}</h3><p>{item.description}</p><p className="journal-origin">{ORIGIN[item.origin.kind]} · créé le {new Date(item.createdAt).toLocaleString('fr-FR')}</p><p className="journal-reason">{item.origin.reason}</p><details><summary>Historique d’évolution ({snapshot.history.filter(event=>event.interestId===item.id).length})</summary>{snapshot.history.filter(event=>event.interestId===item.id).map(event=><p className="history-entry" key={event.id}>{new Date(event.createdAt).toLocaleString('fr-FR')} · {event.action} · {event.previousLevel??'naissance'} → {event.level} · {STATUS[event.status]}<br />{event.reason}</p>)}</details><div className="journal-actions"><button className="text-button" onClick={()=>setDraft({id:item.id,title:item.title,description:item.description,level:item.level,status:item.status})}>Modifier</button><button className="text-button" onClick={()=>{void act(()=>window.aether.blockDomain(item.title,true),'Domaine exclu des prochaines explorations.');}}>Ne plus explorer ce domaine</button>{remove('interest',item.id)}</div></article>)}
    </section>}
    {(tab==='questions'||tab==='discoveries') && <section><h2>{tab==='questions'?'Questions ouvertes et hypothèses':'Synthèses et relations proposées'}</h2>{snapshot.items.filter(item=>tab==='questions'?item.kind!=='discovery':item.kind==='discovery').map(item=><article className="journal-card" data-item-id={item.id} key={item.id}><div className="journal-meta"><span>{item.kind==='question'?'Question ouverte':item.kind==='hypothesis'?`Hypothèse · confiance ${item.confidence}`:'Synthèse locale · non vérifiée'}</span><span>{title(item.interestId)}</span></div><p>{item.content}</p>{item.limits && <p className="journal-limit">{item.limits}</p>}<p className="journal-origin">{new Date(item.createdAt).toLocaleString('fr-FR')} · modèle {snapshot.explorations.find(attempt=>attempt.id===item.explorationId)?.model}</p><div className="journal-actions">{remove(item.kind,item.id)}</div></article>)}{!snapshot.items.some(item=>tab==='questions'?item.kind!=='discovery':item.kind==='discovery') && <p className="journal-empty">Aucune entrée de ce type pour le moment.</p>}</section>}
    {tab==='connections' && <section><h2>Entre deux sujets</h2>{snapshot.connections.map(item=><article className="journal-card connection-card" data-connection-id={item.id} key={item.id}><h3>{title(item.fromId)} ↔ {title(item.toId)}</h3><p>{item.description}</p><p className="journal-limit">Relation proposée par le modèle local ; à vérifier.</p><div className="journal-actions">{remove('connection',item.id)}</div></article>)}{!snapshot.connections.length && <p className="journal-empty">Une exploration peut relier deux intérêts existants, sans inventer de relation déjà établie.</p>}</section>}
    {tab==='explorations' && <section><h2>Les tentatives, y compris leurs limites</h2>{snapshot.explorations.map(item=><article className="journal-card exploration-card" data-exploration-id={item.id} key={item.id}><div className="journal-meta"><span>{item.action} · {item.status}</span><span>{new Date(item.createdAt).toLocaleString('fr-FR')}</span></div><h3>{item.interestId?title(item.interestId):'Naissance d’une piste'}</h3><p>{item.reason}</p>{item.nextQuestion && <p><strong>Ensuite :</strong> {item.nextQuestion}</p>}{item.error && <p className="journal-limit">{item.error}</p>}<p className="journal-origin">{item.route?`${item.route.requested} → ${item.route.selected} · ${item.route.provider} · ${item.model}`:'Aucun résultat modèle reçu'}</p><div className="journal-actions">{remove('exploration',item.id)}</div></article>)}{!snapshot.explorations.length && <p className="journal-empty">Aucune exploration enregistrée.</p>}</section>}
    <section className="domain-controls"><h2>Domaines exclus</h2><form onSubmit={event=>{event.preventDefault();void act(()=>window.aether.blockDomain(domain,true),'Domaine exclu.');setDomain('');}}><label htmlFor="blocked-domain">Domaine ou expression à exclure</label><div><input id="blocked-domain" maxLength={100} minLength={3} required value={domain} onChange={event=>setDomain(event.target.value)} /><button className="secondary" type="submit">Exclure ce domaine</button></div></form><p className="helper">Filtrage des expressions, sans accents ni différence de casse, avant la sélection et après génération. Un domaine exclu ne reçoit pas de nouvelle exploration.</p>{snapshot.blockedDomains.map(value=><div className="blocked-domain" key={value}><span>{value}</span><button className="text-button" onClick={()=>{void act(()=>window.aether.blockDomain(value,false),'Domaine de nouveau autorisé.');}}>Autoriser de nouveau</button></div>)}</section>
  </main>;
}
