import {useEffect,useState} from 'react';
import type {EchoFolderChoice,EchoSnapshot,EchoValidation,OperationResult} from '@aether/shared';

const states={off:'OFF · aucune observation',ready:'Prêt · aucune observation',observing:'Observation autorisée en cours',paused:'En pause · aucune observation',analysing:'MIND interprète la session',error:'Observation arrêtée · erreur'};
const kinds={created:'Création',renamed:'Renommage',moved:'Déplacement',modified:'Modification',deleted:'Suppression'};
const decisions={pending:'À valider',yes:'Confirmée',no:'Refusée',partial:'À préciser',corrected:'Corrigée par vous'};
export function Echo(){
  const [snapshot,setSnapshot]=useState<EchoSnapshot|null>(null),[error,setError]=useState<string|null>(null),[folder,setFolder]=useState<EchoFolderChoice|null>(null),[consent,setConsent]=useState(false),[selected,setSelected]=useState<string|null>(null),[correction,setCorrection]=useState(''),[correcting,setCorrecting]=useState<string|null>(null),[deleting,setDeleting]=useState<string|null>(null),[processes,setProcesses]=useState(''),[windows,setWindows]=useState('');
  useEffect(()=>{void window.aether.getEcho().then(setSnapshot).catch(r=>setError(String(r)));return window.aether.onEcho(setSnapshot);},[]);
  useEffect(()=>{if(snapshot){setProcesses(snapshot.exclusions.processes.join(', '));setWindows(snapshot.exclusions.windows.join(', '));}},[snapshot?.exclusions.processes.join(','),snapshot?.exclusions.windows.join(',')]);
  const action=async(work:()=>Promise<OperationResult>)=>{setError(null);try{const result=await work();if(!result.ok)setError(result.error);}catch(reason){setError(String(reason));}};
  if(!snapshot)return <main className="echo-page"><p>{error??'Chargement ECHO…'}</p></main>;
  const session=snapshot.sessions.find(s=>s.id===(selected??snapshot.activeSessionId))??snapshot.sessions[0],busy=['observing','paused','analysing'].includes(snapshot.state);
  const validation=(hypothesisId:string,decision:EchoValidation['decision'])=>action(()=>window.aether.validateEcho({hypothesisId,decision,...(decision==='correct'?{correction}: {})}));
  return <main className="echo-page">
    <header className="brand"><span className="brand-mark">◌</span><span>AETHER</span><span className="version">ECHO · 05</span></header>
    <div className="echo-heading"><div><p className="eyebrow">APPRENDRE AVEC VOUS</p><h1>Regarde comment je fais.</h1></div><span className={`echo-status ${snapshot.state}`} role="status">{states[snapshot.state]}</span></div>
    <p className="subtle">Vous montrez une méthode, ENTITY propose ce qu’elle croit comprendre. Vous décidez ce qui devient une habitude.</p>
    {(error||snapshot.error)&&<p className="notice" role="alert">{error??snapshot.error}</p>}
    <section className="echo-consent" aria-label="Consentement ECHO">
      {!snapshot.enabled?<button onClick={()=>void action(()=>window.aether.echoControl('enable'))}>Préparer une session ECHO</button>:<>
        {!busy&&<><h2>Une application, un dossier, une session.</h2><p>Windows Explorer uniquement, au premier plan dans le dossier choisi. Noms et chemins relatifs, type, taille, dates et changements de fichiers ; aucun contenu, écran, clavier ou audio. Interprétation par votre modèle local. Chaque lancement exige ce consentement.</p>
          <button className="secondary" onClick={async()=>{setError(null);try{const choice=await window.aether.chooseEchoFolder('session');setFolder(choice);setConsent(false);}catch(reason){setError(String(reason));}}}>Choisir le dossier de test</button>
          {folder&&<p className="echo-resource" data-testid="echo-folder">{folder.folder}</p>}
          <label className="echo-consent-label"><input type="checkbox" checked={consent} disabled={!folder} onChange={e=>setConsent(e.target.checked)}/> J’autorise l’observation de ce dossier dans Explorer pour cette session.</label>
          <button disabled={!folder||!consent} onClick={()=>{const chosen=folder;if(!chosen)return;setConsent(false);setFolder(null);void action(()=>window.aether.startEcho({token:chosen.token,consent:true}));}}>Démarrer l’observation</button>
        </>}
        {busy&&<><h2>{snapshot.state==='analysing'?'Je crois avoir compris…':'À vous de montrer votre méthode.'}</h2><p className="echo-resource">{snapshot.sessions.find(s=>s.id===snapshot.activeSessionId)?.resources.join(' · ')}</p>
          {snapshot.state==='observing'&&<p>{snapshot.context?.reason??'Contexte Explorer en attente.'}</p>}
          <div className="echo-actions">{snapshot.state==='analysing'?<button onClick={()=>void action(()=>window.aether.echoControl('cancel-analysis'))}>Annuler l’interprétation</button>:<><button onClick={()=>void action(()=>window.aether.echoControl('stop'))}>Arrêter et comprendre</button><button className="secondary" onClick={()=>void action(()=>window.aether.echoControl(snapshot.state==='paused'?'resume':'pause'))}>{snapshot.state==='paused'?'Reprendre':'Pause'}</button></>}</div>
        </>}
        <button className="text-button" onClick={()=>{setFolder(null);setConsent(false);void action(()=>window.aether.echoControl('disable'));}}>Désactiver complètement ECHO</button>
      </>}
      <small>Maximum 15 minutes et 600 événements. Fermer ce panneau arrête la perception. ECHO revient OFF au démarrage suivant.</small>
    </section>
    <div className="echo-workspace"><section className="echo-session-list"><h2>Observations récentes</h2>{!snapshot.sessions.length&&<p className="subtle">Aucune session. Rien n’est observé en dehors d’une autorisation.</p>}{snapshot.sessions.map(s=><button className={`echo-session ${s.id===session?.id?'selected':''}`} key={s.id} onClick={()=>{setSelected(s.id);setDeleting(null);setCorrecting(null);}}><strong>{new Date(s.startedAt).toLocaleString('fr-FR')}</strong><span>{s.status} · {s.events.length} événements · {Math.round(s.durationMs/1000)} s</span><small>{s.resources[0]}</small></button>)}</section>
      <section className="echo-session-detail" aria-label="Session ECHO sélectionnée">{session?<><h2>Ce qui a été observé</h2><p className="subtle">{session.applications.join(' · ')} · {session.status}</p>{session.error&&<p role="alert">{session.error}</p>}{session.summary&&<p className="echo-summary">{session.summary}</p>}
        <details open={session.events.length<8}><summary>{session.events.length} événements structurés</summary><ol className="echo-events">{session.events.map(e=><li key={e.id} data-event-id={e.id}><strong>{kinds[e.kind]}</strong> · {e.nodeKind==='directory'?'dossier':'fichier'}<p>{e.previousPath&&<>{e.previousPath} → </>}{e.path}</p><small>{new Date(e.at).toLocaleTimeString('fr-FR')} · {e.windowTitle} · {e.id}</small></li>)}</ol></details>
        {session.hypotheses.map(h=><article className="echo-hypothesis" key={h.id} data-hypothesis-id={h.id}><span className="eyebrow">HYPOTHÈSE · {decisions[h.decision]}</span><h3>{h.interpretation.name}</h3>{h.invalidated?<><p className="subtle"><s>{h.interpretation.description}</s> · interprétation invalidée</p>{h.correction&&<p><strong>Votre correction :</strong> {h.correction}</p>}</>:<p>{h.interpretation.description}</p>}<p className="subtle">Confiance estimée par le modèle : {Math.round(h.interpretation.confidence*100)} % · {snapshot.habits.find(x=>x.id===h.habitId)?.occurrences??0} occurrence(s) · {h.model} / {h.route.selected}</p><ol>{h.interpretation.procedure.map((step,i)=><li key={i}>{step.description}<small className="echo-evidence">Observations : {step.evidenceIds.join(', ')}</small></li>)}</ol>{h.interpretation.variations.map((v,i)=><p key={i}>Suggestion du modèle, à vérifier : {v}</p>)}
          {(h.decision==='pending'||h.decision==='partial')&&<><p>Est-ce bien une méthode que vous utilisez ?</p><div className="echo-actions"><button onClick={()=>void validation(h.id,'yes')}>Oui, retenir cette habitude</button><button className="secondary" onClick={()=>void validation(h.id,'no')}>Non</button><button className="secondary" onClick={()=>void validation(h.id,'partial')}>Partiellement</button></div></>}
          {h.decision!=='no'&&<button className="text-button" onClick={()=>{setCorrecting(h.id);setCorrection(h.correction??'');}}>Corriger l’interprétation</button>}
          {correcting===h.id&&<form onSubmit={e=>{e.preventDefault();void validation(h.id,'correct').then(()=>setCorrecting(null));}}><label htmlFor="echo-correction">Votre méthode réelle</label><textarea id="echo-correction" required minLength={10} maxLength={1200} rows={3} value={correction} onChange={e=>setCorrection(e.target.value)}/><button type="submit">Valider ma correction et retenir</button></form>}
          {h.decision==='partial'&&<p className="subtle">Précisez ou corrigez votre méthode. Cette proposition reste hors MEMORY.</p>}
        </article>)}
        {deleting===session.id?<div className="echo-delete"><p>Supprimer les événements et interprétations de cette session ? Les habitudes sans autre source seront aussi retirées de MEMORY.</p><button className="danger-button" onClick={()=>void action(()=>window.aether.removeEchoSession(session.id)).then(()=>{setSelected(null);setDeleting(null);})}>Confirmer la suppression de session</button><button className="text-button" onClick={()=>setDeleting(null)}>Annuler</button></div>:<button className="text-button" disabled={busy&&session.id===snapshot.activeSessionId} onClick={()=>setDeleting(session.id)}>Supprimer cette session</button>}
      </>:<p className="subtle">Les événements et leur provenance apparaîtront ici.</p>}</section></div>
    <section className="echo-habits"><h2>Habitudes et variations</h2>{snapshot.habits.map(h=><article key={h.id} data-habit-id={h.id}><strong>{h.name}</strong><span>{h.state==='confirmed'?'Confirmée':h.state==='rejected'?'Rejetée':h.state==='dormant'?'En veille':'Hypothèse'} · {h.occurrences} occurrence(s)</span><p>{h.description}</p>{h.memoryId&&<button className="text-button" onClick={()=>void window.aether.command('memory')}>Consulter dans MEMORY</button>}{h.variations.map((v,i)=><p className="subtle" key={i}>{v.description} · {decisions[v.decision]}</p>)}</article>)}{!snapshot.habits.length&&<p className="subtle">Seule votre validation transforme une hypothèse en habitude durable.</p>}{snapshot.opportunities.map(o=><p className="echo-opportunity" key={o.id}>{o.description} Aucune génération ou exécution disponible.</p>)}</section>
    <details className="echo-exclusions"><summary>Exclusions et confidentialité</summary><p>Les autres applications sont toujours hors périmètre. Ajouter une exclusion arrête la session et retire les sessions touchées avec leurs souvenirs dépendants.</p><ul>{snapshot.exclusions.folders.map(path=><li key={path}>{path}<button className="text-button" onClick={()=>void action(()=>window.aether.saveEchoExclusions({...snapshot.exclusions,folders:snapshot.exclusions.folders.filter(x=>x!==path)}))}>Retirer l’exclusion</button></li>)}</ul><button className="secondary" onClick={async()=>{try{const choice=await window.aether.chooseEchoFolder('exclusion');if(choice)await action(()=>window.aether.saveEchoExclusions({...snapshot.exclusions,folders:[...snapshot.exclusions.folders,choice.folder]}));}catch(reason){setError(String(reason));}}}>Exclure un dossier</button><label htmlFor="echo-processes">Processus exclus (séparés par une virgule)</label><input id="echo-processes" value={processes} onChange={e=>setProcesses(e.target.value)}/><label htmlFor="echo-windows">Mots dans les titres de fenêtres exclus</label><input id="echo-windows" value={windows} onChange={e=>setWindows(e.target.value)}/><button className="secondary" onClick={()=>void action(()=>window.aether.saveEchoExclusions({...snapshot.exclusions,processes:processes.split(',').map(x=>x.trim()).filter(Boolean),windows:windows.split(',').map(x=>x.trim()).filter(Boolean)}))}>Enregistrer les exclusions</button><p className="subtle">Données locales dans MEMORY SQLite. Les événements indiquent les changements du dossier pendant un contexte Explorer autorisé ; ils ne prouvent pas qui a modifié les fichiers. Sélections et clics ne sont pas enregistrés.</p></details>
  </main>;
}
