import { useEffect,useState } from 'react';
import type { ModelTarget,RouterConfiguration } from '@aether/shared';
export function RouterSettings() {
  const [configuration,setConfiguration]=useState<RouterConfiguration|null>(null),[notice,setNotice]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
  useEffect(()=>{void window.aether.getModelRouter().then(setConfiguration).catch(reason=>setError(String(reason)));return window.aether.onMind(()=>{void window.aether.getModelRouter().then(setConfiguration).catch(reason=>setError(String(reason)));});},[]);
  return <section className="ai-settings router-settings"><h2>MODEL ROUTER · Profils de capacité</h2><p className="subtle">FAST sert au dialogue. DEEP sert aux explorations. Si DEEP n’est pas configuré, il utilise FAST. CURIOSITY reste locale.</p>
    {configuration && <form onSubmit={async event=>{event.preventDefault();setNotice(null);setError(null);try{const result=await window.aether.saveModelRouter({DEEP:configuration.DEEP,VISION:configuration.VISION});if(result.ok)setNotice('Profils enregistrés.');else setError(result.error);}catch(reason){setError(String(reason));}}}>
      <p className="router-fast">FAST · {configuration.FAST?`${configuration.FAST.provider} / ${configuration.FAST.model}`:'non configuré'} <small>Se configure dans MIND ci-dessus.</small></p>
      {(['DEEP','VISION'] as const).map(profile=><div className="router-profile" key={profile}><h3>{profile}{profile==='VISION'?' · réservé à ECHO, aucune exécution':''}</h3><label htmlFor={`profile-${profile}-provider`}>Fournisseur {profile}</label><select id={`profile-${profile}-provider`} value={configuration[profile]?.provider ?? ''} onChange={event=>setConfiguration({...configuration,[profile]:event.target.value?{provider:event.target.value as ModelTarget['provider'],model:configuration[profile]?.model ?? configuration.FAST?.model ?? ''}:null})}><option value="">{profile==='DEEP'?'Suivre FAST':'Non configuré'}</option><option value="ollama">Ollama · local</option><option value="openai">OpenAI · cloud</option></select>{configuration[profile] && <><label htmlFor={`profile-${profile}-model`}>Modèle {profile}</label><input id={`profile-${profile}-model`} value={configuration[profile]!.model} maxLength={120} onChange={event=>setConfiguration({...configuration,[profile]:{...configuration[profile]!,model:event.target.value}})} /></>}</div>)}
      <p className="helper">Un profil OpenAI exige aussi la clé et le consentement dans MIND. Aucun fallback ne choisit un fournisseur cloud automatiquement. VISION est conservé pour un futur jalon.</p><div className="form-actions"><span>{notice}</span><button type="submit">Enregistrer les profils</button></div>
    </form>}{error && <p role="alert" className="error-message">{error}</p>}
  </section>;
}
