import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import type {PortalSnapshot,PresenceSnapshot,SpaceSelection,SpaceViewWrite} from '@aether/shared';
import {activityEntries,availableCapabilities,DEFAULT_SPACE_PREFERENCES,existingSelection,interestNodes,interestStatusLabel,pan,SPACE_ZONES,zoomAt} from '@aether/space';
import {useSpace} from './useSpace';
import {EntityShape} from './Entity';
import {Memory} from './Memory';
import {SpaceDetails} from './SpaceDetails';

const stateLabels={observing:'ECHO actif',idle:'Au repos',attention:'À votre écoute',thinking:'Réflexion en cours',exploring:'Exploration locale en cours',error:'Échange interrompu'};
const position=(x:number,y:number):CSSProperties=>({left:x,top:y});
export function Space({presence,portal:providedPortal}:{presence:PresenceSnapshot;portal:PortalSnapshot|null}){
  const {snapshot,error}=useSpace();
  const [view,setView]=useState<SpaceViewWrite|null>(null),[query,setQuery]=useState(''),[page,setPage]=useState(0),[pane,setPane]=useState<'objects'|'memory'|'activity'|'capabilities'|'echo'|null>(null),[saveError,setSaveError]=useState<string|null>(null);
  const stage=useRef<HTMLDivElement>(null),currentView=useRef<SpaceViewWrite|null>(null),drag=useRef<{x:number;y:number}|null>(null),saveTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const [activityLimit,setActivityLimit]=useState(100);
  const portal=providedPortal??snapshot?.portal;
  const save=useCallback(async(value:SpaceViewWrite)=>{try{const result=await window.aether.saveSpace(value);if(!result.ok)setSaveError(result.error);}catch(reason){setSaveError(String(reason));}},[]);
  useEffect(()=>{if(snapshot&&!currentView.current){const {camera,labels,depth,selection}=snapshot.preferences;const initial={camera,labels,depth,selection};currentView.current=initial;setView(initial);if(selection)setPane('objects');}},[snapshot]);
  useEffect(()=>{if(view){currentView.current=view;if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{saveTimer.current=undefined;void save(view);},180);}return ()=>{if(saveTimer.current)clearTimeout(saveTimer.current);};},[view,save]);
  useEffect(()=>{if(snapshot&&view?.selection&&!existingSelection(view.selection,snapshot.data))setView({...view,selection:null});},[snapshot,view]);
  useEffect(()=>{if(portal?.phase==='closing'&&currentView.current)void save(currentView.current);},[portal?.phase,save]);
  useEffect(()=>{
    const element=stage.current;if(!element)return;
    function wheel(event:WheelEvent){if((event.target as HTMLElement).closest('[data-no-pan]'))return;event.preventDefault();const bounds=element!.getBoundingClientRect();setView(previous=>previous?{...previous,camera:zoomAt(previous.camera,Math.exp(-event.deltaY*.0015),{x:event.clientX-bounds.left-bounds.width/2,y:event.clientY-bounds.top-bounds.height/2})}:previous);}
    element.addEventListener('wheel',wheel,{passive:false});return ()=>element.removeEventListener('wheel',wheel);
  },[Boolean(snapshot)]);
  const entries=useMemo(()=>snapshot?activityEntries(snapshot.data,snapshot.since):[],[snapshot]),nodes=useMemo(()=>interestNodes(snapshot?.data.curiosity?.interests??[]),[snapshot?.data.curiosity?.interests]);
  const filtered=nodes.filter(node=>`${node.interest.title} ${node.interest.description}`.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))),visible=filtered.slice(page*60,page*60+60),shownIds=new Set(visible.map(node=>node.interest.id));
  const edges=(snapshot?.data.curiosity?.connections??[]).filter(edge=>shownIds.has(edge.fromId)&&shownIds.has(edge.toId));
  const select=(selection:SpaceSelection)=>{setPane('objects');setView(previous=>previous?{...previous,selection}:previous);};
  const focus=(point:{x:number;y:number})=>setView(previous=>previous?{...previous,camera:pan({...previous.camera,x:0,y:0},{x:-point.x*previous.camera.zoom,y:-point.y*previous.camera.zoom})}:previous);
  const close=async()=>{if(currentView.current)await save(currentView.current);await window.aether.portalControl('close');};
  useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();void (async()=>{if(currentView.current)await save(currentView.current);await window.aether.portalControl('close');})();}};window.addEventListener('keydown',escape);return ()=>window.removeEventListener('keydown',escape);},[save]);
  if(!portal)return null;
  const fresh=entries.filter(item=>item.fresh),visual=view??DEFAULT_SPACE_PREFERENCES;
  const shellStyle={'--portal-x':`${portal.origin.x}px`,'--portal-y':`${portal.origin.y}px`,'--core-x':`calc(50% + ${visual.camera.x}px)`,'--core-y':`calc(50% + ${visual.camera.y}px)`,'--core-zoom':visual.camera.zoom,'--portal-radius':`${Math.hypot(portal.viewport.width,portal.viewport.height)+160}px`,'--portal-duration':`${portal.durationMs}ms`} as CSSProperties;
  return <main className={`portal-shell ${portal.reducedMotion||presence.preferences.reducedMotion?'reduce-motion':''}`} style={shellStyle} data-portal-phase={portal.phase} onAnimationEnd={event=>{if(event.animationName==='portal-reveal'||event.animationName==='portal-retract'||event.animationName==='portal-fade-in'||event.animationName==='portal-fade-out')void window.aether.portalControl('settle',portal.token);}} onKeyDown={event=>{
    if((event.target as HTMLElement).closest('input,textarea,select'))return;
    const delta={ArrowLeft:{x:80,y:0},ArrowRight:{x:-80,y:0},ArrowUp:{x:0,y:80},ArrowDown:{x:0,y:-80}}[event.key];
    if(delta){event.preventDefault();setView(previous=>previous?{...previous,camera:pan(previous.camera,delta)}:previous);}
    if(event.key==='Home'||event.key==='0'){event.preventDefault();setView(previous=>previous?{...previous,camera:{x:0,y:0,zoom:.86}}:previous);}
  }}>
    {portal.phase!=='open'&&<div className="portal-traveller"><EntityShape id="portal-traveller"/></div>}
    <div className={`space-universe ${visual.depth?'space-depth':''} ${visual.labels?'':'space-hide-labels'}`}>
      <header className="space-header"><div className="space-brand"><span>◌</span><h1>AETHER</h1><small>SPACE · 05</small></div><div className="space-entity-badge"><EntityShape id="space-badge"/><span>ENTITY · {stateLabels[presence.state]}</span>{presence.discoveryPending&&<i>Une réflexion à partager</i>}</div><button className="space-exit" onClick={()=>{void close();}}>Revenir au bureau <kbd>Échap</kbd></button></header>
      <nav className="space-zones" aria-label="Zones de SPACE"><button onClick={()=>{setPane('memory');focus(SPACE_ZONES.memory);}}>MEMORY</button><button onClick={()=>{setPane(null);focus(SPACE_ZONES.curiosity);}}>CURIOSITY</button><button onClick={()=>{setPane('echo');focus(SPACE_ZONES.echo);}}>ECHO</button><button onClick={()=>setPane('activity')}>ACTIVITY <span>{fresh.length}</span></button><button onClick={()=>setPane('capabilities')}>CAPABILITIES</button></nav>
      <div ref={stage} className="space-stage" tabIndex={0} aria-label="Univers spatial d’ENTITY" aria-describedby="space-navigation-help" data-zoom={visual.camera.zoom.toFixed(3)} onPointerDown={event=>{if(event.button!==0||(event.target as HTMLElement).closest('[data-no-pan]'))return;drag.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(!drag.current)return;const delta={x:event.clientX-drag.current.x,y:event.clientY-drag.current.y};drag.current={x:event.clientX,y:event.clientY};setView(previous=>previous?{...previous,camera:pan(previous.camera,delta)}:previous);}} onPointerUp={event=>{drag.current=null;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}} onPointerCancel={()=>{drag.current=null;}}>
        <div className="space-world" style={{transform:`translate(${visual.camera.x}px,${visual.camera.y}px) scale(${visual.camera.zoom})`}}>
          <div className="space-orbit space-orbit-near"/><div className="space-orbit space-orbit-far"/>
          {!!snapshot?.data.echo?.habits.some(h=>h.memoryId)&&<svg className="space-connections space-echo-link" viewBox="-2200 -2000 4400 4000" aria-label="Habitudes ECHO reliées à MEMORY"><path className="space-edge" d={`M ${SPACE_ZONES.echo.x} ${SPACE_ZONES.echo.y} Q 0 460 ${SPACE_ZONES.memory.x} ${SPACE_ZONES.memory.y}`}/></svg>}
          <section className="space-echo-island space-island" style={position(SPACE_ZONES.echo.x,SPACE_ZONES.echo.y)} data-no-pan aria-label="ECHO dans SPACE"><p className="space-eyebrow">ECHO</p><h2>Ce que vous m’apprenez</h2><span className="space-count">{snapshot?.data.echo?.habits.filter(h=>h.state==='confirmed').length??0} habitudes confirmées</span>{snapshot?.data.echo?.habits.slice(0,3).map(h=><button className="space-memory-object" key={h.id} data-habit-id={h.id} onClick={()=>select({kind:'habit',id:h.id})}>{h.name}<small>{h.state==='confirmed'?'Confirmée':'Hypothèse'} · {h.occurrences} occurrence(s)</small></button>)}{!snapshot?.data.echo?.habits.length&&<p className="space-empty">L’observation commence avec votre consentement.</p>}<button className="space-island-action" onClick={()=>setPane('echo')}>Sessions, hypothèses et variations →</button></section>
          <button className="space-core" style={position(0,0)} data-no-pan aria-label="Dialoguer avec ENTITY" onClick={()=>{void window.aether.command('dialogue');}}><div className={`entity-stage ${presence.preferences.reducedMotion?'reduce-motion':''}`} data-state={presence.state} data-discovery-pending={presence.discoveryPending?'true':'false'}><EntityShape id="space-core"/></div><strong>ENTITY</strong><small>{stateLabels[presence.state]}</small></button>
          <section className="space-memory-island space-island" style={position(SPACE_ZONES.memory.x,SPACE_ZONES.memory.y)} data-no-pan aria-label="Souvenirs dans SPACE"><p className="space-eyebrow">MEMORY</p><h2>Ce que je garde</h2><span className="space-count">{snapshot?.data.memories.length??0} souvenirs durables</span>{snapshot?.data.memories.slice(0,5).map(memory=><button className="space-memory-object" data-memory-id={memory.id} key={memory.id} onClick={()=>select({kind:'memory',id:memory.id})}>{memory.content}<small>{memory.origin==='explicit'?'Donné explicitement':'Hypothèse'}</small></button>)}{!snapshot?.data.memories.length&&<p className="space-empty">Aucun souvenir enregistré.</p>}<button className="space-island-action" onClick={()=>setPane('memory')}>Consulter et corriger →</button></section>
          <section className="space-curiosity-label" style={position(390,-310)} data-no-pan><p className="space-eyebrow">CURIOSITY</p><h2>Ce qui m’intéresse</h2><span>{nodes.length} pistes · {snapshot?.data.curiosity?.items.filter(item=>item.kind==='question').length??0} questions ouvertes</span>{!nodes.length&&<p className="space-empty">Aucune piste pré-écrite. Le journal se remplit avec les explorations autorisées.</p>}</section>
          <svg className="space-connections" viewBox="-2200 -2000 4400 4000" aria-label="Connexions entre intérêts">{edges.map(edge=>{const from=nodes.find(node=>node.interest.id===edge.fromId)!,to=nodes.find(node=>node.interest.id===edge.toId)!,mid={x:(from.position.x+to.position.x)/2,y:(from.position.y+to.position.y)/2};return <g key={edge.id} data-no-pan data-connection-id={edge.id} role="button" tabIndex={0} aria-label={`Connexion ${from.interest.title} — ${to.interest.title}`} onClick={()=>select({kind:'connection',id:edge.id})} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select({kind:'connection',id:edge.id});}}}><path className="space-edge-hit" d={`M ${from.position.x} ${from.position.y} Q ${mid.x} ${mid.y-50} ${to.position.x} ${to.position.y}`}/><path className={`space-edge ${visual.selection?.id===edge.id?'selected':''}`} d={`M ${from.position.x} ${from.position.y} Q ${mid.x} ${mid.y-50} ${to.position.x} ${to.position.y}`}/><circle cx={mid.x} cy={mid.y-25} r={5}/></g>;})}</svg>
          {visible.map(node=><button className={`space-interest-node ${visual.selection?.id===node.interest.id?'selected':''} ${node.interest.status}`} key={node.interest.id} data-interest-id={node.interest.id} data-no-pan style={{...position(node.position.x,node.position.y),'--node-radius':`${node.radius}px`} as CSSProperties} aria-label={`Intérêt ${node.interest.title}`} onClick={()=>select({kind:'interest',id:node.interest.id})}><span className="space-node-light"/><strong>{node.interest.title}</strong><small>{Math.round(node.interest.level*100)} % · {interestStatusLabel[node.interest.status]}</small></button>)}
          <section className="space-activity-island space-island" style={position(SPACE_ZONES.activity.x,SPACE_ZONES.activity.y)} data-no-pan><p className="space-eyebrow">ACTIVITY</p><h2>{snapshot?.since?'Depuis votre dernière visite':'Les premières traces'}</h2><p className="space-activity-summary">{fresh.length} événements issus du journal réel</p>{(fresh.length?fresh:entries).slice(0,3).map(item=><button className="space-activity-object" key={item.id} onClick={()=>{if(item.target)select(item.target);else setPane('activity');}}><span>{item.kind}</span><strong>{item.title}</strong><small>{new Date(item.at).toLocaleString('fr-FR')}{item.transient?' · session seulement':''}</small></button>)}{!entries.length&&<p className="space-empty">Aucune activité enregistrée.</p>}<button className="space-island-action" onClick={()=>setPane('activity')}>Parcourir les traces →</button></section>
          <section className="space-capability-island" style={position(SPACE_ZONES.capabilities.x,SPACE_ZONES.capabilities.y)} data-no-pan><p className="space-eyebrow">CAPABILITIES</p><h2>Ce que je peux faire</h2><div>{snapshot&&availableCapabilities(snapshot.data).filter(item=>item.available).map(item=><span key={item.key}>{item.name}</span>)}</div><button className="space-island-action" onClick={()=>setPane('capabilities')}>Voir les capacités réelles →</button></section>
        </div>
      </div>
      <div className="space-search" data-no-pan><label htmlFor="space-interest-search">Trouver une piste</label><input id="space-interest-search" placeholder="Titre ou sujet…" value={query} maxLength={100} onChange={event=>{setQuery(event.target.value);setPage(0);}} onKeyDown={event=>{if(event.key==='Enter'&&filtered[0]){event.preventDefault();focus(filtered[0].position);select({kind:'interest',id:filtered[0].interest.id});}}}/>{filtered.length>60&&<div><button disabled={page===0} onClick={()=>setPage(value=>value-1)}>Précédentes</button><span>{page*60+1}–{Math.min(filtered.length,(page+1)*60)} / {filtered.length}</span><button disabled={(page+1)*60>=filtered.length} onClick={()=>setPage(value=>value+1)}>Suivantes</button></div>}{query&&!filtered.length&&<small>Aucune piste correspondante.</small>}</div>
      <div className="space-navigation"><button aria-label="Dézoomer" onClick={()=>setView(previous=>previous?{...previous,camera:zoomAt(previous.camera,1/1.15,{x:0,y:0})}:previous)}>−</button><span>{Math.round(visual.camera.zoom*100)} %</span><button aria-label="Zoomer" onClick={()=>setView(previous=>previous?{...previous,camera:zoomAt(previous.camera,1.15,{x:0,y:0})}:previous)}>+</button><button className="space-center-button" onClick={()=>setView(previous=>previous?{...previous,camera:{x:0,y:0,zoom:.86}}:previous)}>Revenir au centre</button><details><summary>Affichage</summary><label><input type="checkbox" checked={visual.labels} onChange={event=>setView(previous=>previous?{...previous,labels:event.target.checked}:previous)}/> Libellés des pistes</label><label><input type="checkbox" checked={visual.depth} onChange={event=>setView(previous=>previous?{...previous,depth:event.target.checked}:previous)}/> Profondeur légère</label></details></div>
      <p id="space-navigation-help" className="space-navigation-help">Glisser le fond · Molette pour zoomer · Flèches pour naviguer · Home pour recentrer</p>
      {(error||saveError)&&<p className="space-error" role="alert">{error||saveError}</p>}
      {pane&&snapshot&&<aside className="space-inspector" aria-label="Détails de l’objet sélectionné" data-no-pan><header><span>{pane==='memory'?'MEMORY':pane==='activity'?'ACTIVITY':pane==='capabilities'?'CAPABILITIES':pane==='echo'?'ECHO':'OBJET SÉLECTIONNÉ'}</span><button aria-label="Fermer les détails" onClick={()=>{setPane(null);setView(previous=>previous?{...previous,selection:null}:previous);}}>×</button></header><div className="space-inspector-body">
        {pane==='echo'&&<><p className="space-eyebrow">ECHO · APPRENTISSAGE GUIDÉ</p><h2>Vos méthodes et leurs sources</h2><button className="space-secondary" onClick={()=>void window.aether.command('echo')}>Regarde comment je fais</button><h3>Observations récentes</h3>{snapshot.data.echo?.sessions.map(s=><button className="space-object-row" key={s.id} onClick={()=>select({kind:'echo-session',id:s.id})}>{new Date(s.startedAt).toLocaleString('fr-FR')} · {s.events.length} événements</button>)}<h3>Hypothèses</h3>{snapshot.data.echo?.habits.filter(h=>h.state==='hypothesis').map(h=><button className="space-object-row" key={h.id} onClick={()=>select({kind:'habit',id:h.id})}>{h.name}</button>)}<h3>Habitudes confirmées</h3>{snapshot.data.echo?.habits.filter(h=>h.state==='confirmed').map(h=><button className="space-object-row" key={h.id} onClick={()=>select({kind:'habit',id:h.id})}>{h.name} · {h.occurrences} occurrence(s)</button>)}<h3>Variations</h3>{snapshot.data.echo?.habits.flatMap(h=>h.variations.map((v,i)=><p key={`${h.id}:${i}`}>{h.name} : {v.description} · {v.decision}</p>))}<p className="space-limit">Seules les habitudes confirmées sont accessibles à MIND. L’ouverture de ce panneau n’autorise aucune observation.</p></>}
        {pane==='echo'?null:pane==='memory'?<Memory embedded/>:pane==='activity'?<><p className="space-eyebrow">HISTOIRE RÉELLE</p><h2>{snapshot.since?'Depuis votre dernière visite':'Le journal d’ENTITY'}</h2><p>{fresh.length} événements nouveaux · {snapshot.since?new Date(snapshot.since).toLocaleString('fr-FR'):'première visite'}</p>{entries.slice(0,activityLimit).map(item=><article className="space-detail-row" data-activity-id={item.id} key={item.id}><span>{item.kind}{item.fresh?' · nouveau':''}</span><h3>{item.title}</h3><p>{item.detail}</p><small>{new Date(item.at).toLocaleString('fr-FR')}{item.transient?' · échange non persistant':''}</small>{item.target&&<button className="space-secondary" onClick={()=>select(item.target!)}>Voir l’objet</button>}</article>)}{entries.length>activityLimit&&<button className="space-secondary" onClick={()=>setActivityLimit(value=>value+100)}>Afficher plus de traces ({activityLimit} / {entries.length})</button>}{!entries.length&&<p>Aucune activité enregistrée.</p>}</>:pane==='capabilities'?<><p className="space-eyebrow">CAPACITÉS RÉELLES</p><h2>Ce qui est disponible</h2>{availableCapabilities(snapshot.data).map(item=><article className="space-detail-row" key={item.key}><h3>{item.name} · {item.available?'disponible':'indisponible'}</h3><p>{item.description}</p></article>)}<h3>Futures · indisponibles</h3><p>FORGE, MIRROR, plugins et nouvelles capacités générées.</p><p className="space-limit">ECHO exige une session explicitement autorisée.</p></>:visual.selection?<SpaceDetails selection={visual.selection} data={snapshot.data} onSelect={select} onMemory={()=>setPane('memory')}/>:<p>Cet objet n’est plus présent dans la base active.</p>}
      </div></aside>}
    </div>
  </main>;
}
