import {interestStatusLabel,explorationStatusLabel} from '@aether/space';
import type {SpaceData,SpaceSelection} from '@aether/shared';

const originNames={autonomous:'Réflexion autonome',conversation:'Conversation',memory:'Souvenir local',mind:'Suggestion de MIND',interest:'Intérêt précédent',connection:'Connexion',exploration:'Exploration précédente',user:'Piste proposée dans le journal'};
export function SpaceDetails({selection,data,onSelect,onMemory}:{selection:SpaceSelection;data:SpaceData;onSelect:(value:SpaceSelection)=>void;onMemory:()=>void}){
  const journal=data.curiosity,title=(id:string|null)=>journal?.interests.find(item=>item.id===id)?.title??'Piste retirée';
  const links=(id:string)=>journal?.connections.filter(item=>item.fromId===id||item.toId===id)??[];
  if(selection.kind==='habit'){
    const habit=data.echo?.habits.find(h=>h.id===selection.id);if(!habit)return <p>Cette habitude a été retirée.</p>;
    return <><p className="space-eyebrow">ECHO · {habit.state==='confirmed'?'HABITUDE CONFIRMÉE':'HYPOTHÈSE'}</p><h2>{habit.name}</h2><p>{habit.description}</p><p>{habit.occurrences} occurrence(s) · confiance estimée {Math.round(habit.confidence*100)} %</p><p>{habit.context}</p><ol>{habit.procedure.map((s,i)=><li key={i}>{s.description}</li>)}</ol>{habit.variations.map((v,i)=><p key={i}>Variation mesurée : {v.description} · {v.decision}<small className="echo-evidence">Observations : {v.evidenceIds.join(', ')}</small></p>)}<div className="space-linked-objects">{habit.memoryId&&<button onClick={()=>onSelect({kind:'memory',id:habit.memoryId!})}>Souvenir confirmé dans MEMORY</button>}{habit.provenance.sessionIds.map(id=><button key={id} onClick={()=>onSelect({kind:'echo-session',id})}>Session source · {id.slice(0,8)}</button>)}</div><button className="space-secondary" onClick={()=>void window.aether.command('echo')}>Ouvrir ECHO pour valider ou corriger</button></>;
  }
  if(selection.kind==='echo-session'){
    const session=data.echo?.sessions.find(s=>s.id===selection.id);if(!session)return <p>Cette session a été supprimée.</p>;
    return <><p className="space-eyebrow">ECHO · OBSERVATION AUTORISÉE</p><h2>{new Date(session.startedAt).toLocaleString('fr-FR')}</h2><p>{session.resources[0]}</p><p>{session.events.length} événements · {session.status} · {Math.round(session.durationMs/1000)} s</p><p>{session.summary??'Pas d’interprétation disponible.'}</p>{session.hypotheses.map(h=><button className="space-object-row" key={h.id} onClick={()=>onSelect({kind:'habit',id:h.habitId})}>{h.correction??h.interpretation.name} · {h.decision}</button>)}<button className="space-secondary" onClick={()=>void window.aether.command('echo')}>Consulter les événements et décisions dans ECHO</button></>;
  }
  if(selection.kind==='memory'){
    const memory=data.memories.find(item=>item.id===selection.id);if(!memory)return <p>Ce souvenir a été retiré.</p>;
    return <><p className="space-eyebrow">MEMORY · {memory.origin==='explicit'?'Déclaration explicite':'Hypothèse'}</p><h2>Un souvenir conservé</h2><p className="space-original">{memory.content}</p><p className="space-provenance">{memory.source}<br />{new Date(memory.updatedAt).toLocaleString('fr-FR')}{memory.confidence!==null?` · confiance ${memory.confidence}`:''}</p><button className="space-secondary" onClick={onMemory}>Corriger ou supprimer dans MEMORY</button></>;
  }
  if(selection.kind==='interest'){
    const item=journal?.interests.find(item=>item.id===selection.id);if(!item||!journal)return <p>Cette piste a été retirée.</p>;
    const questions=journal.items.filter(value=>value.interestId===item.id&&value.kind==='question'),discoveries=journal.items.filter(value=>value.interestId===item.id&&value.kind==='discovery'),attempts=journal.explorations.filter(value=>value.interestId===item.id||value.targets.includes(item.id)),history=journal.history.filter(value=>value.interestId===item.id);
    return <><p className="space-eyebrow">CURIOSITY · {interestStatusLabel[item.status]}</p><h2>{item.title}</h2><p>{item.description}</p><p className="space-provenance">Priorité cognitive {Math.round(item.level*100)} % · {originNames[item.origin.kind]}<br />Créé le {new Date(item.createdAt).toLocaleString('fr-FR')}</p><p>{item.origin.reason}</p>
      <section aria-label="Historique de l’intérêt"><h3>Historique · {history.length}</h3>{history.map(event=><article className="space-detail-row" key={event.id}><span>{event.action} · {event.previousLevel??'naissance'} → {event.level} · {interestStatusLabel[event.status]}</span><p>{event.reason}</p><small>{new Date(event.createdAt).toLocaleString('fr-FR')}</small></article>)}</section>
      <section aria-label="Questions de l’intérêt"><h3>Ce que j’essaie de comprendre · {questions.length}</h3>{questions.map(value=><button className="space-object-row" key={value.id} onClick={()=>onSelect({kind:'question',id:value.id})}>{value.content}</button>)}</section>
      <section aria-label="Découvertes de l’intérêt"><h3>Résultats proposés · {discoveries.length}</h3>{discoveries.map(value=><button className="space-object-row" key={value.id} onClick={()=>onSelect({kind:'discovery',id:value.id})}>{value.content}</button>)}</section>
      <section aria-label="Connexions de l’intérêt"><h3>Connexions · {links(item.id).length}</h3>{links(item.id).map(value=><button className="space-object-row" key={value.id} onClick={()=>onSelect({kind:'connection',id:value.id})}>{title(value.fromId)} ↔ {title(value.toId)}</button>)}</section>
      <section aria-label="Explorations de l’intérêt"><h3>Explorations · {attempts.length}</h3>{attempts.map(value=><button className="space-object-row" key={value.id} onClick={()=>onSelect({kind:'exploration',id:value.id})}>{value.action} · {explorationStatusLabel[value.status]} · {new Date(value.createdAt).toLocaleString('fr-FR')}</button>)}</section><button className="space-secondary" onClick={()=>{void window.aether.command('curiosity');}}>Ouvrir le journal complet</button></>;
  }
  if(selection.kind==='connection'){
    const edge=journal?.connections.find(item=>item.id===selection.id);if(!edge)return <p>Cette connexion a été retirée.</p>;
    return <><p className="space-eyebrow">CONNEXION · RELATION PROPOSÉE</p><h2>{title(edge.fromId)} ↔ {title(edge.toId)}</h2><p className="space-original">{edge.description}</p><p className="space-provenance">{new Date(edge.createdAt).toLocaleString('fr-FR')} · synthèse du modèle, non vérifiée.</p><div className="space-linked-objects"><button onClick={()=>onSelect({kind:'interest',id:edge.fromId})}>{title(edge.fromId)}</button><button onClick={()=>onSelect({kind:'interest',id:edge.toId})}>{title(edge.toId)}</button><button onClick={()=>onSelect({kind:'exploration',id:edge.explorationId})}>Voir l’exploration source</button></div></>;
  }
  if(selection.kind==='exploration'){
    const attempt=journal?.explorations.find(item=>item.id===selection.id);if(!attempt)return <p>Cette exploration a été retirée.</p>;
    return <><p className="space-eyebrow">EXPLORATION · {explorationStatusLabel[attempt.status]}</p><h2>{title(attempt.interestId)}</h2><p>{attempt.reason}</p>{attempt.error&&<p className="space-limit">{attempt.error}</p>}<p className="space-provenance">{attempt.route?`${attempt.route.requested} → ${attempt.route.selected} · ${attempt.route.provider} · ${attempt.model}`:'Aucun résultat modèle reçu'}<br />{new Date(attempt.createdAt).toLocaleString('fr-FR')}</p>{journal?.items.filter(item=>item.explorationId===attempt.id).map(item=><article className="space-detail-row" key={item.id}><h3>{item.kind==='question'?'Question':item.kind==='hypothesis'?`Hypothèse · confiance ${item.confidence}`:'Résultat proposé'}</h3><p>{item.content}</p>{item.limits&&<p className="space-limit">{item.limits}</p>}</article>)}{attempt.nextQuestion&&<p><strong>Ensuite :</strong> {attempt.nextQuestion}</p>}</>;
  }
  const item=journal?.items.find(value=>value.id===selection.id&&value.kind===selection.kind);if(!item)return <p>Cet objet a été retiré.</p>;
  return <><p className="space-eyebrow">{item.kind==='question'?'QUESTION OUVERTE':item.kind==='hypothesis'?'HYPOTHÈSE':'DÉCOUVERTE · SYNTHÈSE NON VÉRIFIÉE'}</p><h2>{title(item.interestId)}</h2><p className="space-original">{item.content}</p>{item.confidence!==null&&<p>Confiance estimée : {item.confidence}</p>}{item.limits&&<p className="space-limit">{item.limits}</p>}<button className="space-secondary" onClick={()=>onSelect({kind:'exploration',id:item.explorationId})}>Voir l’exploration source</button><button className="space-secondary" onClick={()=>onSelect({kind:'interest',id:item.interestId})}>Revenir à l’intérêt</button></>;
}
