import { _electron } from 'playwright';
import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import { listPackage } from '@electron/asar';
import { writeFile } from 'node:fs/promises';

const executable = resolve('release/AETHER-win32-x64/AETHER.exe');
const files = listPackage(resolve('release/AETHER-win32-x64/resources/app.asar'));
assert(files.includes('\\dist\\main\\main.cjs'));
assert(!files.some(path => path.startsWith('\\node_modules') || path.startsWith('\\tests') || path.startsWith('\\apps')));
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const application = await _electron.launch({ executablePath: executable, env });
try {
  const page = await application.firstWindow();
  await page.getByRole('button', { name: 'ENTITY — cliquer ou déplacer' }).waitFor();
  const runtime = await application.evaluate(({ app, BrowserWindow }) => ({ packaged: app.isPackaged, windows: BrowserWindow.getAllWindows().length, appPath: app.getAppPath(), visible: BrowserWindow.getAllWindows()[0].isVisible() }));
  assert.equal(runtime.packaged, true);
  const snapshot = await page.evaluate(() => window.aether.getSnapshot());
  assert.equal(snapshot.features.presence, 'available');
  assert.equal(snapshot.features.mind, 'available');
  assert.equal(snapshot.features.memory, 'available');
  assert.equal(snapshot.features.curiosity, 'available');
  assert(Object.values(snapshot.permissions).every(value => value === false));
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  await page.evaluate(() => window.aether.command('recall'));
  await page.evaluate(() => window.aether.command('settings'));
  const settings = application.windows().find(window => window !== page);
  assert(settings); await settings.getByRole('heading', { name: 'ENTITY, sur votre bureau' }).waitFor();
  const configuration = await settings.evaluate(() => window.aether.getAiConfiguration());
  assert.equal('apiKey' in configuration, false);
  assert.equal(configuration.provider, 'ollama');
  assert.equal(configuration.cloudConsent, false);
  assert.equal(configuration.model, 'qwen3.5:9b');
  const router=await page.evaluate(()=>window.aether.getModelRouter());
  assert.deepEqual(router.FAST,{provider:'ollama',model:'qwen3.5:9b'});
  assert.deepEqual(router.DEEP,{provider:'ollama',model:'qwen3.5:9b'});
  const curiosity=await page.evaluate(()=>window.aether.getCuriosity());
  assert.equal(curiosity.settings.enabled,false);
  assert.equal(curiosity.interests.length,0);
  await settings.screenshot({path:'docs/recette-j3/paquet-profils.png',fullPage:true});
  await page.evaluate(() => window.aether.command('dialogue'));
  const dialogue = application.windows().find(window => window.url().endsWith('#dialogue'));
  assert(dialogue); await dialogue.getByRole('textbox', { name: 'Message à ENTITY' }).waitFor();
  const result = await dialogue.evaluate(() => window.aether.sendMessage('Comment t’appelles-tu ?'));
  assert.equal(result.ok, true);
  const mind = await dialogue.evaluate(() => window.aether.getMind());
  const answer = mind.messages.at(-1);
  assert.equal(answer.role, 'assistant');
  assert.match(answer.content, /ENTITY/i);
  assert.equal(answer.model, 'qwen3.5:9b');
  const version = await application.evaluate(({ app }) => app.getVersion());
  assert.equal(version, '0.3.0');
  assert.equal((await page.evaluate(()=>window.aether.getCuriosity())).explorations.length,0);
  const evidence={ result: 'PASS', checkedAt:new Date().toISOString(), version, executable, runtime, configuration, router, curiosity:{enabled:curiosity.settings.enabled,interests:curiosity.interests.length}, answer, shortcutRegistered: snapshot.shortcutRegistered, preferences: snapshot.preferences, packagedEntries: files.length };
  await writeFile('docs/recette-j3/paquet-verifie.json',JSON.stringify(evidence,null,2));
  console.log(JSON.stringify(evidence, null, 2));
} finally { await application.close(); }
