import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, renameSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { EchoEngine, EchoRepository, FileObserver, DEFAULT_EXCLUSIONS, measuredVariations, parseExclusions, signature, similarity, validateRoot, type ContextSource, type ObserverPort } from '@aether/echo';
import { EchoInterpreter, parseEchoInterpretation } from '@aether/mind';
import { SqliteMemoryRepository } from '@aether/memory';
import { PresenceModel, DEFAULT_PREFERENCES } from '@aether/core';
import type { EchoContext, EchoEvent, EchoInterpretation, EchoInterpreterPort, Habit } from '@aether/shared';
const route={requested:'DEEP',selected:'DEEP',provider:'unit-test',model:'unit-test',fallback:false} as const;
const event=(id='event-1',root='C:\\test'):EchoEvent=>({id,sessionId:'session',at:new Date().toISOString(),kind:'renamed',path:'2026-10-05_audio.wav',previousPath:'audio.wav',nodeKind:'file',size:5,source:'filesystem',application:'explorer.exe',windowTitle:'test',contextFolder:root});
const interpretation=(events:EchoEvent[]):EchoInterpretation=>({summary:'Classement audio par date.',name:'Organisation audio',description:'Je classe les fichiers audio par date.',context:'Dossier Explorer autorisé',triggers:['fichiers WAV'],procedure:[{action:'renamed',description:'Renommer le fichier avec une date.',evidenceIds:events.map(e=>e.id)}],evidenceIds:events.map(e=>e.id),confidence:.7,matchedHabitId:null,variations:[]});
class Observer implements ObserverPort {starts=0;closed=0;emit:((events:EchoEvent[])=>void)|null=null;start(_root:string,_id:string,_ex:unknown,emit:(events:EchoEvent[])=>void){this.starts++;this.emit=emit;}close(){this.closed++;}}
function setup(interpreter?:EchoInterpreterPort){const root=mkdtempSync(join(tmpdir(),'aether-echo-unit-')),repo=new EchoRepository(':memory:'),observer=new Observer(),engine=new EchoEngine(repo,observer,interpreter??{async interpret(events){return {interpretation:interpretation(events),model:'unit-test',route};}});return {root,repo,observer,engine,cleanup:()=>{engine.close();rmSync(root,{recursive:true,force:true});}};}
async function record(s:ReturnType<typeof setup>,id='event-1'){s.engine.enable();const grant=s.engine.choose(s.root);s.engine.start({token:grant.token,consent:true});s.observer.emit!([event(id,s.root)]);await s.engine.stop();return s.engine.snapshot().sessions[0]!;}

test('ECHO requires explicit consent and a fresh native-folder token; defaults OFF',()=>{const s=setup();try{assert.equal(s.engine.snapshot().state,'off');assert.equal(s.observer.starts,0);assert.throws(()=>s.engine.start({token:'fake',consent:true}));s.engine.enable();const g=s.engine.choose(s.root);assert.throws(()=>s.engine.start({token:g.token,consent:false} as never));s.engine.start({token:g.token,consent:true});assert.equal(s.observer.starts,1);s.engine.disable();assert.throws(()=>s.engine.start({token:g.token,consent:true}));}finally{s.cleanup();}});
test('hypotheses remain outside MEMORY until a human approves; partial/no are not approvals',async()=>{const s=setup();try{const session=await record(s);assert.equal(s.repo.habits()[0]!.memoryId,null);const hypothesisId=session.hypotheses[0]!.id;s.engine.validate({hypothesisId,decision:'partial'});assert.equal(s.repo.habits()[0]!.memoryId,null);s.engine.validate({hypothesisId,decision:'yes'});assert.equal(s.repo.habits()[0]!.state,'confirmed');assert(s.repo.habits()[0]!.memoryId);assert.throws(()=>s.engine.validate({hypothesisId,decision:'yes'}));}finally{s.cleanup();}});
test('repeated procedure reuses a habit; pending variations do not replace its approved meaning',async()=>{const s=setup();try{let session=await record(s);s.engine.validate({hypothesisId:session.hypotheses[0]!.id,decision:'yes'});const original=s.repo.habits()[0]!;session=await record(s,'event-2');assert.equal(s.repo.habits().length,1);assert.equal(s.repo.habits()[0]!.id,original.id);assert.equal(s.repo.habits()[0]!.occurrences,2);assert.equal(s.repo.habits()[0]!.description,original.description);assert.equal(s.repo.opportunities()[0]!.executionAllowed,false);}finally{s.cleanup();}});
test('user correction invalidates the original and confirmed habit exposes only the corrected intention',async()=>{const s=setup();try{const session=await record(s),id=session.hypotheses[0]!.id;const corrected='Je prépare un export client, sans classer ma bibliothèque audio.';s.engine.validate({hypothesisId:id,decision:'correct',correction:corrected});assert.equal(s.repo.habits()[0]!.description,corrected);assert.equal(s.repo.session(session.id).hypotheses[0]!.invalidated,true);assert.match(s.repo.session(session.id).summary!,/Correction/);assert.equal(s.repo.habits()[0]!.state,'confirmed');}finally{s.cleanup();}});
test('a rejected interpretation is invalidated and not proposed again for the same procedure',async()=>{const s=setup();try{const session=await record(s);s.engine.validate({hypothesisId:session.hypotheses[0]!.id,decision:'no'});await record(s,'event-2');assert.equal(s.repo.sessions()[0]!.hypotheses.length,0);assert.equal(s.repo.habits().length,1);assert.equal(s.repo.habits()[0]!.state,'rejected');}finally{s.cleanup();}});
test('deleting a sole source removes its events, hypothesis, habit, opportunity and actual MEMORY/FTS row',async()=>{const root=mkdtempSync(join(tmpdir(),'aether-echo-db-')),path=join(root,'memory.sqlite'),repo=new EchoRepository(path),mem=new SqliteMemoryRepository(path);try{const session=repo.create(root),e={...event('e',root),sessionId:session.id};repo.append(session.id,[e]);repo.status(session.id,'analysing');const h=repo.propose(session.id,{interpretation:interpretation([e]),model:'unit-test',route})!;repo.validate({hypothesisId:h.id,decision:'yes'});assert.equal((await mem.list())[0]!.kind,'habit');repo.removeSession(session.id);assert.deepEqual(repo.sessions(),[]);assert.deepEqual(repo.habits(),[]);assert.deepEqual(await mem.list(),[]);assert.deepEqual(await mem.search('audio'),[]);}finally{repo.close();mem.close();rmSync(root,{recursive:true,force:true});}});
test('deleting one repeated source retains another approved source and recomputes the occurrence count',async()=>{const s=setup();try{const first=await record(s);s.engine.validate({hypothesisId:first.hypotheses[0]!.id,decision:'yes'});const second=await record(s,'event-2');s.engine.validate({hypothesisId:second.hypotheses[0]!.id,decision:'yes'});s.engine.removeSession(second.id);assert.equal(s.repo.habits()[0]!.occurrences,1);assert.equal(s.repo.habits()[0]!.state,'confirmed');assert.deepEqual(s.repo.habits()[0]!.provenance.sessionIds,[first.id]);}finally{s.cleanup();}});
test('disable and deletion cancel pending interpretation and discard late model output',async()=>{let release!:(value:Awaited<ReturnType<EchoInterpreterPort['interpret']>>)=>void;const pending=new Promise<Awaited<ReturnType<EchoInterpreterPort['interpret']>>>(r=>release=r);const s=setup({interpret:()=>pending});try{s.engine.enable();const g=s.engine.choose(s.root);s.engine.start({token:g.token,consent:true});const events=[event('e',s.root)];s.observer.emit!(events);const stopped=s.engine.stop();s.engine.disable();release({interpretation:interpretation(events),model:'unit-test',route});await stopped;assert.equal(s.engine.snapshot().state,'off');assert.equal(s.repo.habits().length,0);assert.equal(s.repo.sessions()[0]!.status,'interrupted');const count=s.repo.sessions()[0]!.events.length;s.observer.emit!([event('late',s.root)]);assert.equal(s.repo.sessions()[0]!.events.length,count);}finally{s.cleanup();}});
test('exclusion is checked again before human confirmation and retracts dependent memories',async()=>{const s=setup();try{const session=await record(s);s.engine.validate({hypothesisId:session.hypotheses[0]!.id,decision:'yes'});s.engine.configure({...DEFAULT_EXCLUSIONS,folders:[s.root]});assert.equal(s.repo.sessions().length,0);assert.equal(s.repo.habits().length,0);assert.throws(()=>s.engine.validate({hypothesisId:session.hypotheses[0]!.id,decision:'yes'}));assert.throws(()=>{const g=s.engine.choose(s.root);s.engine.start({token:g.token,consent:true});});}finally{s.cleanup();}});
test('paused observations and excluded paths/processes/windows cannot enter the event journal',async()=>{const s=setup();try{s.engine.configure({...DEFAULT_EXCLUSIONS,folders:[join(s.root,'private')]});s.engine.enable();const g=s.engine.choose(s.root);s.engine.start({token:g.token,consent:true});s.observer.emit!([{...event('secret',s.root),path:'private/secret.wav'}, {...event('external',s.root),path:'../outside.wav'},{...event('bank',s.root),windowTitle:'banque'},{...event('browser',s.root),application:'chrome.exe' as never}]);assert.equal(s.repo.sessions()[0]!.events.length,0);s.engine.pause();s.observer.emit!([event('paused',s.root)]);assert.equal(s.repo.sessions()[0]!.events.length,0);}finally{s.cleanup();}});
test('actual file observer detects rename/move/create without reading content; excluded subtree is absent',async()=>{const root=mkdtempSync(join(tmpdir(),'aether-echo-files-')),privateDir=join(root,'private');mkdirSync(privateDir);writeFileSync(join(root,'sample.wav'),'unit-test');const context:EchoContext={allowed:true,application:'explorer.exe',folder:root,windowTitle:'test',reason:'unit-test'};const source:ContextSource={current:()=>context,start(){},close(){}};const observer=new FileObserver(source),events:EchoEvent[]=[];try{observer.start(root,'session',{...DEFAULT_EXCLUSIONS,folders:[privateDir]},e=>events.push(...e),()=>{},e=>{throw e;});renameSync(join(root,'sample.wav'),join(root,'2026-10-05_sample.wav'));await new Promise(r=>setTimeout(r,350));mkdirSync(join(root,'2026-10-05'));await new Promise(r=>setTimeout(r,350));renameSync(join(root,'2026-10-05_sample.wav'),join(root,'2026-10-05','2026-10-05_sample.wav'));writeFileSync(join(privateDir,'secret.wav'),'secret');await new Promise(r=>setTimeout(r,350));assert(events.some(e=>e.kind==='renamed'));assert(events.some(e=>e.kind==='created'&&e.nodeKind==='directory'));assert(events.some(e=>e.kind==='moved'));assert(!events.some(e=>e.path.includes('private')));assert(!('content' in events[0]!));observer.close();writeFileSync(join(root,'after-off.txt'),'unit-test');const n=events.length;await new Promise(r=>setTimeout(r,250));assert.equal(events.length,n);}finally{observer.close();rmSync(root,{recursive:true,force:true});}});
test('JSON interpretation rejects invented evidence, nonexistent habits and unobserved step kinds',()=>{const events=[event()],p=interpretation(events);assert.deepEqual(parseEchoInterpretation(JSON.stringify(p),events,[]),p);assert.throws(()=>parseEchoInterpretation(JSON.stringify({...p,evidenceIds:['invented']}),events,[]));assert.throws(()=>parseEchoInterpretation(JSON.stringify({...p,matchedHabitId:'fake'}),events,[]));assert.throws(()=>parseEchoInterpretation(JSON.stringify({...p,procedure:[{...p.procedure[0],action:'moved'}]}),events,[]));});
test('MIND ECHO always requests local DEEP with structured actual evidence and never executes tools',async()=>{const events=[event()];let seen=false;const interpreter=new EchoInterpreter({async complete(profile,request,options){seen=true;assert.equal(profile,'DEEP');assert.equal(options?.localOnly,true);assert.equal(request.responseFormat,'json');assert(request.messages[1]!.content.includes(events[0]!.id));return {text:JSON.stringify(interpretation(events)),model:'unit-test',route};}});await interpreter.interpret(events,[] as Habit[],new AbortController().signal);assert(seen);});
test('schema v3 migrates without changing J1-J4 records and never persists session consent',()=>{const root=mkdtempSync(join(tmpdir(),'aether-echo-migrate-')),path=join(root,'memory.sqlite');const repo=new EchoRepository(path);try{const db=new DatabaseSync(path,{readOnly:true});assert.equal(db.prepare('PRAGMA user_version').get()!.user_version,3);assert.equal(Number(db.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE name LIKE 'echo_%'").get()!.n)>0,true);db.close();assert(!('enabled' in repo.exclusions()));}finally{repo.close();rmSync(root,{recursive:true,force:true});}});
test('PRESENCE signals observation only when ECHO is available and explicitly active',()=>{const model=new PresenceModel(structuredClone(DEFAULT_PREFERENCES),true,true,true,true,true);assert.equal(model.snapshot().permissions['echo.observe'],false);model.setEchoActive(true);model.setState('observing');assert.equal(model.snapshot().echoActive,true);assert.equal(model.snapshot().permissions['files.read'],true);assert.equal(model.snapshot().permissions['files.write'],false);model.setEchoActive(false);assert.equal(model.snapshot().permissions['echo.observe'],false);});
test('scope and exclusions reject broad roots, network paths, unknown fields; signature ignores literal filenames',()=>{assert.throws(()=>validateRoot('C:\\'));assert.throws(()=>validateRoot('\\\\server\\share'));assert.throws(()=>parseExclusions({folders:[],processes:[],windows:[],capture:true}));assert.equal(similarity(signature([event()]),signature([{...event(),path:'2026-11-08_voice.wav'}])),1);});
test('variations in a habit are measured from actual events rather than speculative model suggestions',()=>{const repo=new EchoRepository(':memory:');try{const first=repo.create('C:\\test'),a={...event('first'),sessionId:first.id};repo.append(first.id,[a]);repo.status(first.id,'analysing');const p=repo.propose(first.id,{interpretation:{...interpretation([a]),variations:['Une variation inventée par le modèle.']},model:'unit-test',route})!;repo.validate({hypothesisId:p.id,decision:'yes'});const second=repo.create('C:\\test'),b={...event('second'),path:'2026-10-08_audio.wav',sessionId:second.id};repo.append(second.id,[b]);repo.status(second.id,'analysing');repo.propose(second.id,{interpretation:{...interpretation([b]),variations:['Des sous-dossiers mensuels qui ne sont pas observés.']},model:'unit-test',route});const variation=repo.habits()[0]!.variations[0]!;assert.match(variation.description,/2026-10-05.*2026-10-08/);assert.deepEqual(variation.evidenceIds,['second']);assert.equal(variation.comparedSessionId,first.id);assert.equal(repo.habits()[0]!.variations.some(v=>v.description.includes('inventée')||v.description.includes('mensuels')),false);assert.equal(measuredVariations(repo.session(first.id),repo.session(first.id),'yes').length,0);}finally{repo.close();}});
